# REQUIRED: provider is the name of the provider without the pulumi-prefix e.g. "aws".
provider: ibmcloud
# The name of the GitHub organization or username the repository lives in. Defaults to 'pulumi'
organization: mapt-oss
# The external template only includes workflows relevant for non-Pulumi managed providers.
template: external-bridged-provider
# The name of the GitHub organisation or username where the upstream terraform provider lives.
upstreamProviderOrg: IBM-Cloud
# major version of the current provider - used in make files
# This should always be set by all providers as this is key to go module paths.
major-version: 1
# Enable using the terraform converter for example generation.
pulumiConvert: 1
# Set a GitHub username here for automatic upgrade PRs to be assigned to.
# pr-assign: pulumi-bot

# providerDefaultBranch is used to customise the default branch for the repo
providerDefaultBranch: main
# Only Go SDK - others are generated but not published
languages:
    - go
# Disable all SDK publishing - binaries only on GitHub releases
publish:
    sdk: "none"
    cdn: false
# Enables automatic generation of basic docs pages for the registry.
# registryDocs: true

# Disables a pulumi-internal-only step for running create_docs_build during the release
publishRegistry: false

# Disable ESC for CI secrets - not publishing to external registries
esc:
    enabled: false
