// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ibmcloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/mapt-oss/pulumi-ibmcloud/sdk/go/ibmcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CdTektonPipelineDefinition struct {
	pulumi.CustomResourceState

	// The aggregated definition ID.
	DefinitionId pulumi.StringOutput `pulumi:"definitionId"`
	// API URL for interacting with the definition.
	Href pulumi.StringOutput `pulumi:"href"`
	// The Tekton pipeline ID.
	PipelineId pulumi.StringOutput `pulumi:"pipelineId"`
	// Source repository containing the Tekton pipeline definition.
	Source CdTektonPipelineDefinitionSourceOutput `pulumi:"source"`
}

// NewCdTektonPipelineDefinition registers a new resource with the given unique name, arguments, and options.
func NewCdTektonPipelineDefinition(ctx *pulumi.Context,
	name string, args *CdTektonPipelineDefinitionArgs, opts ...pulumi.ResourceOption) (*CdTektonPipelineDefinition, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PipelineId == nil {
		return nil, errors.New("invalid value for required argument 'PipelineId'")
	}
	if args.Source == nil {
		return nil, errors.New("invalid value for required argument 'Source'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CdTektonPipelineDefinition
	err := ctx.RegisterResource("ibmcloud:index/cdTektonPipelineDefinition:CdTektonPipelineDefinition", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCdTektonPipelineDefinition gets an existing CdTektonPipelineDefinition resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCdTektonPipelineDefinition(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CdTektonPipelineDefinitionState, opts ...pulumi.ResourceOption) (*CdTektonPipelineDefinition, error) {
	var resource CdTektonPipelineDefinition
	err := ctx.ReadResource("ibmcloud:index/cdTektonPipelineDefinition:CdTektonPipelineDefinition", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CdTektonPipelineDefinition resources.
type cdTektonPipelineDefinitionState struct {
	// The aggregated definition ID.
	DefinitionId *string `pulumi:"definitionId"`
	// API URL for interacting with the definition.
	Href *string `pulumi:"href"`
	// The Tekton pipeline ID.
	PipelineId *string `pulumi:"pipelineId"`
	// Source repository containing the Tekton pipeline definition.
	Source *CdTektonPipelineDefinitionSource `pulumi:"source"`
}

type CdTektonPipelineDefinitionState struct {
	// The aggregated definition ID.
	DefinitionId pulumi.StringPtrInput
	// API URL for interacting with the definition.
	Href pulumi.StringPtrInput
	// The Tekton pipeline ID.
	PipelineId pulumi.StringPtrInput
	// Source repository containing the Tekton pipeline definition.
	Source CdTektonPipelineDefinitionSourcePtrInput
}

func (CdTektonPipelineDefinitionState) ElementType() reflect.Type {
	return reflect.TypeOf((*cdTektonPipelineDefinitionState)(nil)).Elem()
}

type cdTektonPipelineDefinitionArgs struct {
	// The Tekton pipeline ID.
	PipelineId string `pulumi:"pipelineId"`
	// Source repository containing the Tekton pipeline definition.
	Source CdTektonPipelineDefinitionSource `pulumi:"source"`
}

// The set of arguments for constructing a CdTektonPipelineDefinition resource.
type CdTektonPipelineDefinitionArgs struct {
	// The Tekton pipeline ID.
	PipelineId pulumi.StringInput
	// Source repository containing the Tekton pipeline definition.
	Source CdTektonPipelineDefinitionSourceInput
}

func (CdTektonPipelineDefinitionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cdTektonPipelineDefinitionArgs)(nil)).Elem()
}

type CdTektonPipelineDefinitionInput interface {
	pulumi.Input

	ToCdTektonPipelineDefinitionOutput() CdTektonPipelineDefinitionOutput
	ToCdTektonPipelineDefinitionOutputWithContext(ctx context.Context) CdTektonPipelineDefinitionOutput
}

func (*CdTektonPipelineDefinition) ElementType() reflect.Type {
	return reflect.TypeOf((**CdTektonPipelineDefinition)(nil)).Elem()
}

func (i *CdTektonPipelineDefinition) ToCdTektonPipelineDefinitionOutput() CdTektonPipelineDefinitionOutput {
	return i.ToCdTektonPipelineDefinitionOutputWithContext(context.Background())
}

func (i *CdTektonPipelineDefinition) ToCdTektonPipelineDefinitionOutputWithContext(ctx context.Context) CdTektonPipelineDefinitionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CdTektonPipelineDefinitionOutput)
}

// CdTektonPipelineDefinitionArrayInput is an input type that accepts CdTektonPipelineDefinitionArray and CdTektonPipelineDefinitionArrayOutput values.
// You can construct a concrete instance of `CdTektonPipelineDefinitionArrayInput` via:
//
//	CdTektonPipelineDefinitionArray{ CdTektonPipelineDefinitionArgs{...} }
type CdTektonPipelineDefinitionArrayInput interface {
	pulumi.Input

	ToCdTektonPipelineDefinitionArrayOutput() CdTektonPipelineDefinitionArrayOutput
	ToCdTektonPipelineDefinitionArrayOutputWithContext(context.Context) CdTektonPipelineDefinitionArrayOutput
}

type CdTektonPipelineDefinitionArray []CdTektonPipelineDefinitionInput

func (CdTektonPipelineDefinitionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CdTektonPipelineDefinition)(nil)).Elem()
}

func (i CdTektonPipelineDefinitionArray) ToCdTektonPipelineDefinitionArrayOutput() CdTektonPipelineDefinitionArrayOutput {
	return i.ToCdTektonPipelineDefinitionArrayOutputWithContext(context.Background())
}

func (i CdTektonPipelineDefinitionArray) ToCdTektonPipelineDefinitionArrayOutputWithContext(ctx context.Context) CdTektonPipelineDefinitionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CdTektonPipelineDefinitionArrayOutput)
}

// CdTektonPipelineDefinitionMapInput is an input type that accepts CdTektonPipelineDefinitionMap and CdTektonPipelineDefinitionMapOutput values.
// You can construct a concrete instance of `CdTektonPipelineDefinitionMapInput` via:
//
//	CdTektonPipelineDefinitionMap{ "key": CdTektonPipelineDefinitionArgs{...} }
type CdTektonPipelineDefinitionMapInput interface {
	pulumi.Input

	ToCdTektonPipelineDefinitionMapOutput() CdTektonPipelineDefinitionMapOutput
	ToCdTektonPipelineDefinitionMapOutputWithContext(context.Context) CdTektonPipelineDefinitionMapOutput
}

type CdTektonPipelineDefinitionMap map[string]CdTektonPipelineDefinitionInput

func (CdTektonPipelineDefinitionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CdTektonPipelineDefinition)(nil)).Elem()
}

func (i CdTektonPipelineDefinitionMap) ToCdTektonPipelineDefinitionMapOutput() CdTektonPipelineDefinitionMapOutput {
	return i.ToCdTektonPipelineDefinitionMapOutputWithContext(context.Background())
}

func (i CdTektonPipelineDefinitionMap) ToCdTektonPipelineDefinitionMapOutputWithContext(ctx context.Context) CdTektonPipelineDefinitionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CdTektonPipelineDefinitionMapOutput)
}

type CdTektonPipelineDefinitionOutput struct{ *pulumi.OutputState }

func (CdTektonPipelineDefinitionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CdTektonPipelineDefinition)(nil)).Elem()
}

func (o CdTektonPipelineDefinitionOutput) ToCdTektonPipelineDefinitionOutput() CdTektonPipelineDefinitionOutput {
	return o
}

func (o CdTektonPipelineDefinitionOutput) ToCdTektonPipelineDefinitionOutputWithContext(ctx context.Context) CdTektonPipelineDefinitionOutput {
	return o
}

// The aggregated definition ID.
func (o CdTektonPipelineDefinitionOutput) DefinitionId() pulumi.StringOutput {
	return o.ApplyT(func(v *CdTektonPipelineDefinition) pulumi.StringOutput { return v.DefinitionId }).(pulumi.StringOutput)
}

// API URL for interacting with the definition.
func (o CdTektonPipelineDefinitionOutput) Href() pulumi.StringOutput {
	return o.ApplyT(func(v *CdTektonPipelineDefinition) pulumi.StringOutput { return v.Href }).(pulumi.StringOutput)
}

// The Tekton pipeline ID.
func (o CdTektonPipelineDefinitionOutput) PipelineId() pulumi.StringOutput {
	return o.ApplyT(func(v *CdTektonPipelineDefinition) pulumi.StringOutput { return v.PipelineId }).(pulumi.StringOutput)
}

// Source repository containing the Tekton pipeline definition.
func (o CdTektonPipelineDefinitionOutput) Source() CdTektonPipelineDefinitionSourceOutput {
	return o.ApplyT(func(v *CdTektonPipelineDefinition) CdTektonPipelineDefinitionSourceOutput { return v.Source }).(CdTektonPipelineDefinitionSourceOutput)
}

type CdTektonPipelineDefinitionArrayOutput struct{ *pulumi.OutputState }

func (CdTektonPipelineDefinitionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CdTektonPipelineDefinition)(nil)).Elem()
}

func (o CdTektonPipelineDefinitionArrayOutput) ToCdTektonPipelineDefinitionArrayOutput() CdTektonPipelineDefinitionArrayOutput {
	return o
}

func (o CdTektonPipelineDefinitionArrayOutput) ToCdTektonPipelineDefinitionArrayOutputWithContext(ctx context.Context) CdTektonPipelineDefinitionArrayOutput {
	return o
}

func (o CdTektonPipelineDefinitionArrayOutput) Index(i pulumi.IntInput) CdTektonPipelineDefinitionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CdTektonPipelineDefinition {
		return vs[0].([]*CdTektonPipelineDefinition)[vs[1].(int)]
	}).(CdTektonPipelineDefinitionOutput)
}

type CdTektonPipelineDefinitionMapOutput struct{ *pulumi.OutputState }

func (CdTektonPipelineDefinitionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CdTektonPipelineDefinition)(nil)).Elem()
}

func (o CdTektonPipelineDefinitionMapOutput) ToCdTektonPipelineDefinitionMapOutput() CdTektonPipelineDefinitionMapOutput {
	return o
}

func (o CdTektonPipelineDefinitionMapOutput) ToCdTektonPipelineDefinitionMapOutputWithContext(ctx context.Context) CdTektonPipelineDefinitionMapOutput {
	return o
}

func (o CdTektonPipelineDefinitionMapOutput) MapIndex(k pulumi.StringInput) CdTektonPipelineDefinitionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CdTektonPipelineDefinition {
		return vs[0].(map[string]*CdTektonPipelineDefinition)[vs[1].(string)]
	}).(CdTektonPipelineDefinitionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CdTektonPipelineDefinitionInput)(nil)).Elem(), &CdTektonPipelineDefinition{})
	pulumi.RegisterInputType(reflect.TypeOf((*CdTektonPipelineDefinitionArrayInput)(nil)).Elem(), CdTektonPipelineDefinitionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CdTektonPipelineDefinitionMapInput)(nil)).Elem(), CdTektonPipelineDefinitionMap{})
	pulumi.RegisterOutputType(CdTektonPipelineDefinitionOutput{})
	pulumi.RegisterOutputType(CdTektonPipelineDefinitionArrayOutput{})
	pulumi.RegisterOutputType(CdTektonPipelineDefinitionMapOutput{})
}
