// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ibmcloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/mapt-oss/pulumi-ibmcloud/sdk/go/ibmcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type EnSubscriptionPagerduty struct {
	pulumi.CustomResourceState

	Attributes EnSubscriptionPagerdutyAttributesPtrOutput `pulumi:"attributes"`
	// Subscription description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Destination ID.
	DestinationId pulumi.StringOutput `pulumi:"destinationId"`
	// The Destintion name.
	DestinationName pulumi.StringOutput `pulumi:"destinationName"`
	// The type of Destination.
	DestinationType pulumi.StringOutput `pulumi:"destinationType"`
	// Unique identifier for IBM Cloud Event Notifications instance.
	InstanceGuid pulumi.StringOutput `pulumi:"instanceGuid"`
	// Subscription name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Subscription ID.
	SubscriptionId pulumi.StringOutput `pulumi:"subscriptionId"`
	// Topic ID.
	TopicId pulumi.StringOutput `pulumi:"topicId"`
	// Name of the topic.
	TopicName pulumi.StringOutput `pulumi:"topicName"`
	// Last updated time.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewEnSubscriptionPagerduty registers a new resource with the given unique name, arguments, and options.
func NewEnSubscriptionPagerduty(ctx *pulumi.Context,
	name string, args *EnSubscriptionPagerdutyArgs, opts ...pulumi.ResourceOption) (*EnSubscriptionPagerduty, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DestinationId == nil {
		return nil, errors.New("invalid value for required argument 'DestinationId'")
	}
	if args.InstanceGuid == nil {
		return nil, errors.New("invalid value for required argument 'InstanceGuid'")
	}
	if args.TopicId == nil {
		return nil, errors.New("invalid value for required argument 'TopicId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource EnSubscriptionPagerduty
	err := ctx.RegisterResource("ibmcloud:index/enSubscriptionPagerduty:EnSubscriptionPagerduty", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEnSubscriptionPagerduty gets an existing EnSubscriptionPagerduty resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEnSubscriptionPagerduty(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EnSubscriptionPagerdutyState, opts ...pulumi.ResourceOption) (*EnSubscriptionPagerduty, error) {
	var resource EnSubscriptionPagerduty
	err := ctx.ReadResource("ibmcloud:index/enSubscriptionPagerduty:EnSubscriptionPagerduty", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering EnSubscriptionPagerduty resources.
type enSubscriptionPagerdutyState struct {
	Attributes *EnSubscriptionPagerdutyAttributes `pulumi:"attributes"`
	// Subscription description.
	Description *string `pulumi:"description"`
	// Destination ID.
	DestinationId *string `pulumi:"destinationId"`
	// The Destintion name.
	DestinationName *string `pulumi:"destinationName"`
	// The type of Destination.
	DestinationType *string `pulumi:"destinationType"`
	// Unique identifier for IBM Cloud Event Notifications instance.
	InstanceGuid *string `pulumi:"instanceGuid"`
	// Subscription name.
	Name *string `pulumi:"name"`
	// Subscription ID.
	SubscriptionId *string `pulumi:"subscriptionId"`
	// Topic ID.
	TopicId *string `pulumi:"topicId"`
	// Name of the topic.
	TopicName *string `pulumi:"topicName"`
	// Last updated time.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type EnSubscriptionPagerdutyState struct {
	Attributes EnSubscriptionPagerdutyAttributesPtrInput
	// Subscription description.
	Description pulumi.StringPtrInput
	// Destination ID.
	DestinationId pulumi.StringPtrInput
	// The Destintion name.
	DestinationName pulumi.StringPtrInput
	// The type of Destination.
	DestinationType pulumi.StringPtrInput
	// Unique identifier for IBM Cloud Event Notifications instance.
	InstanceGuid pulumi.StringPtrInput
	// Subscription name.
	Name pulumi.StringPtrInput
	// Subscription ID.
	SubscriptionId pulumi.StringPtrInput
	// Topic ID.
	TopicId pulumi.StringPtrInput
	// Name of the topic.
	TopicName pulumi.StringPtrInput
	// Last updated time.
	UpdatedAt pulumi.StringPtrInput
}

func (EnSubscriptionPagerdutyState) ElementType() reflect.Type {
	return reflect.TypeOf((*enSubscriptionPagerdutyState)(nil)).Elem()
}

type enSubscriptionPagerdutyArgs struct {
	Attributes *EnSubscriptionPagerdutyAttributes `pulumi:"attributes"`
	// Subscription description.
	Description *string `pulumi:"description"`
	// Destination ID.
	DestinationId string `pulumi:"destinationId"`
	// Unique identifier for IBM Cloud Event Notifications instance.
	InstanceGuid string `pulumi:"instanceGuid"`
	// Subscription name.
	Name *string `pulumi:"name"`
	// Topic ID.
	TopicId string `pulumi:"topicId"`
}

// The set of arguments for constructing a EnSubscriptionPagerduty resource.
type EnSubscriptionPagerdutyArgs struct {
	Attributes EnSubscriptionPagerdutyAttributesPtrInput
	// Subscription description.
	Description pulumi.StringPtrInput
	// Destination ID.
	DestinationId pulumi.StringInput
	// Unique identifier for IBM Cloud Event Notifications instance.
	InstanceGuid pulumi.StringInput
	// Subscription name.
	Name pulumi.StringPtrInput
	// Topic ID.
	TopicId pulumi.StringInput
}

func (EnSubscriptionPagerdutyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*enSubscriptionPagerdutyArgs)(nil)).Elem()
}

type EnSubscriptionPagerdutyInput interface {
	pulumi.Input

	ToEnSubscriptionPagerdutyOutput() EnSubscriptionPagerdutyOutput
	ToEnSubscriptionPagerdutyOutputWithContext(ctx context.Context) EnSubscriptionPagerdutyOutput
}

func (*EnSubscriptionPagerduty) ElementType() reflect.Type {
	return reflect.TypeOf((**EnSubscriptionPagerduty)(nil)).Elem()
}

func (i *EnSubscriptionPagerduty) ToEnSubscriptionPagerdutyOutput() EnSubscriptionPagerdutyOutput {
	return i.ToEnSubscriptionPagerdutyOutputWithContext(context.Background())
}

func (i *EnSubscriptionPagerduty) ToEnSubscriptionPagerdutyOutputWithContext(ctx context.Context) EnSubscriptionPagerdutyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnSubscriptionPagerdutyOutput)
}

// EnSubscriptionPagerdutyArrayInput is an input type that accepts EnSubscriptionPagerdutyArray and EnSubscriptionPagerdutyArrayOutput values.
// You can construct a concrete instance of `EnSubscriptionPagerdutyArrayInput` via:
//
//	EnSubscriptionPagerdutyArray{ EnSubscriptionPagerdutyArgs{...} }
type EnSubscriptionPagerdutyArrayInput interface {
	pulumi.Input

	ToEnSubscriptionPagerdutyArrayOutput() EnSubscriptionPagerdutyArrayOutput
	ToEnSubscriptionPagerdutyArrayOutputWithContext(context.Context) EnSubscriptionPagerdutyArrayOutput
}

type EnSubscriptionPagerdutyArray []EnSubscriptionPagerdutyInput

func (EnSubscriptionPagerdutyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EnSubscriptionPagerduty)(nil)).Elem()
}

func (i EnSubscriptionPagerdutyArray) ToEnSubscriptionPagerdutyArrayOutput() EnSubscriptionPagerdutyArrayOutput {
	return i.ToEnSubscriptionPagerdutyArrayOutputWithContext(context.Background())
}

func (i EnSubscriptionPagerdutyArray) ToEnSubscriptionPagerdutyArrayOutputWithContext(ctx context.Context) EnSubscriptionPagerdutyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnSubscriptionPagerdutyArrayOutput)
}

// EnSubscriptionPagerdutyMapInput is an input type that accepts EnSubscriptionPagerdutyMap and EnSubscriptionPagerdutyMapOutput values.
// You can construct a concrete instance of `EnSubscriptionPagerdutyMapInput` via:
//
//	EnSubscriptionPagerdutyMap{ "key": EnSubscriptionPagerdutyArgs{...} }
type EnSubscriptionPagerdutyMapInput interface {
	pulumi.Input

	ToEnSubscriptionPagerdutyMapOutput() EnSubscriptionPagerdutyMapOutput
	ToEnSubscriptionPagerdutyMapOutputWithContext(context.Context) EnSubscriptionPagerdutyMapOutput
}

type EnSubscriptionPagerdutyMap map[string]EnSubscriptionPagerdutyInput

func (EnSubscriptionPagerdutyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EnSubscriptionPagerduty)(nil)).Elem()
}

func (i EnSubscriptionPagerdutyMap) ToEnSubscriptionPagerdutyMapOutput() EnSubscriptionPagerdutyMapOutput {
	return i.ToEnSubscriptionPagerdutyMapOutputWithContext(context.Background())
}

func (i EnSubscriptionPagerdutyMap) ToEnSubscriptionPagerdutyMapOutputWithContext(ctx context.Context) EnSubscriptionPagerdutyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnSubscriptionPagerdutyMapOutput)
}

type EnSubscriptionPagerdutyOutput struct{ *pulumi.OutputState }

func (EnSubscriptionPagerdutyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EnSubscriptionPagerduty)(nil)).Elem()
}

func (o EnSubscriptionPagerdutyOutput) ToEnSubscriptionPagerdutyOutput() EnSubscriptionPagerdutyOutput {
	return o
}

func (o EnSubscriptionPagerdutyOutput) ToEnSubscriptionPagerdutyOutputWithContext(ctx context.Context) EnSubscriptionPagerdutyOutput {
	return o
}

func (o EnSubscriptionPagerdutyOutput) Attributes() EnSubscriptionPagerdutyAttributesPtrOutput {
	return o.ApplyT(func(v *EnSubscriptionPagerduty) EnSubscriptionPagerdutyAttributesPtrOutput { return v.Attributes }).(EnSubscriptionPagerdutyAttributesPtrOutput)
}

// Subscription description.
func (o EnSubscriptionPagerdutyOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EnSubscriptionPagerduty) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Destination ID.
func (o EnSubscriptionPagerdutyOutput) DestinationId() pulumi.StringOutput {
	return o.ApplyT(func(v *EnSubscriptionPagerduty) pulumi.StringOutput { return v.DestinationId }).(pulumi.StringOutput)
}

// The Destintion name.
func (o EnSubscriptionPagerdutyOutput) DestinationName() pulumi.StringOutput {
	return o.ApplyT(func(v *EnSubscriptionPagerduty) pulumi.StringOutput { return v.DestinationName }).(pulumi.StringOutput)
}

// The type of Destination.
func (o EnSubscriptionPagerdutyOutput) DestinationType() pulumi.StringOutput {
	return o.ApplyT(func(v *EnSubscriptionPagerduty) pulumi.StringOutput { return v.DestinationType }).(pulumi.StringOutput)
}

// Unique identifier for IBM Cloud Event Notifications instance.
func (o EnSubscriptionPagerdutyOutput) InstanceGuid() pulumi.StringOutput {
	return o.ApplyT(func(v *EnSubscriptionPagerduty) pulumi.StringOutput { return v.InstanceGuid }).(pulumi.StringOutput)
}

// Subscription name.
func (o EnSubscriptionPagerdutyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *EnSubscriptionPagerduty) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Subscription ID.
func (o EnSubscriptionPagerdutyOutput) SubscriptionId() pulumi.StringOutput {
	return o.ApplyT(func(v *EnSubscriptionPagerduty) pulumi.StringOutput { return v.SubscriptionId }).(pulumi.StringOutput)
}

// Topic ID.
func (o EnSubscriptionPagerdutyOutput) TopicId() pulumi.StringOutput {
	return o.ApplyT(func(v *EnSubscriptionPagerduty) pulumi.StringOutput { return v.TopicId }).(pulumi.StringOutput)
}

// Name of the topic.
func (o EnSubscriptionPagerdutyOutput) TopicName() pulumi.StringOutput {
	return o.ApplyT(func(v *EnSubscriptionPagerduty) pulumi.StringOutput { return v.TopicName }).(pulumi.StringOutput)
}

// Last updated time.
func (o EnSubscriptionPagerdutyOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *EnSubscriptionPagerduty) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type EnSubscriptionPagerdutyArrayOutput struct{ *pulumi.OutputState }

func (EnSubscriptionPagerdutyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EnSubscriptionPagerduty)(nil)).Elem()
}

func (o EnSubscriptionPagerdutyArrayOutput) ToEnSubscriptionPagerdutyArrayOutput() EnSubscriptionPagerdutyArrayOutput {
	return o
}

func (o EnSubscriptionPagerdutyArrayOutput) ToEnSubscriptionPagerdutyArrayOutputWithContext(ctx context.Context) EnSubscriptionPagerdutyArrayOutput {
	return o
}

func (o EnSubscriptionPagerdutyArrayOutput) Index(i pulumi.IntInput) EnSubscriptionPagerdutyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *EnSubscriptionPagerduty {
		return vs[0].([]*EnSubscriptionPagerduty)[vs[1].(int)]
	}).(EnSubscriptionPagerdutyOutput)
}

type EnSubscriptionPagerdutyMapOutput struct{ *pulumi.OutputState }

func (EnSubscriptionPagerdutyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EnSubscriptionPagerduty)(nil)).Elem()
}

func (o EnSubscriptionPagerdutyMapOutput) ToEnSubscriptionPagerdutyMapOutput() EnSubscriptionPagerdutyMapOutput {
	return o
}

func (o EnSubscriptionPagerdutyMapOutput) ToEnSubscriptionPagerdutyMapOutputWithContext(ctx context.Context) EnSubscriptionPagerdutyMapOutput {
	return o
}

func (o EnSubscriptionPagerdutyMapOutput) MapIndex(k pulumi.StringInput) EnSubscriptionPagerdutyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *EnSubscriptionPagerduty {
		return vs[0].(map[string]*EnSubscriptionPagerduty)[vs[1].(string)]
	}).(EnSubscriptionPagerdutyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EnSubscriptionPagerdutyInput)(nil)).Elem(), &EnSubscriptionPagerduty{})
	pulumi.RegisterInputType(reflect.TypeOf((*EnSubscriptionPagerdutyArrayInput)(nil)).Elem(), EnSubscriptionPagerdutyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EnSubscriptionPagerdutyMapInput)(nil)).Elem(), EnSubscriptionPagerdutyMap{})
	pulumi.RegisterOutputType(EnSubscriptionPagerdutyOutput{})
	pulumi.RegisterOutputType(EnSubscriptionPagerdutyArrayOutput{})
	pulumi.RegisterOutputType(EnSubscriptionPagerdutyMapOutput{})
}
