// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ibmcloud

import (
	"context"
	"reflect"

	"github.com/mapt-oss/pulumi-ibmcloud/sdk/go/ibmcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupAppidTokenConfig(ctx *pulumi.Context, args *LookupAppidTokenConfigArgs, opts ...pulumi.InvokeOption) (*LookupAppidTokenConfigResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAppidTokenConfigResult
	err := ctx.Invoke("ibmcloud:index/getAppidTokenConfig:getAppidTokenConfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAppidTokenConfig.
type LookupAppidTokenConfigArgs struct {
	TenantId string `pulumi:"tenantId"`
}

// A collection of values returned by getAppidTokenConfig.
type LookupAppidTokenConfigResult struct {
	AccessTokenClaims       []GetAppidTokenConfigAccessTokenClaim `pulumi:"accessTokenClaims"`
	AccessTokenExpiresIn    int                                   `pulumi:"accessTokenExpiresIn"`
	AnonymousAccessEnabled  bool                                  `pulumi:"anonymousAccessEnabled"`
	AnonymousTokenExpiresIn int                                   `pulumi:"anonymousTokenExpiresIn"`
	// The provider-assigned unique ID for this managed resource.
	Id                    string                            `pulumi:"id"`
	IdTokenClaims         []GetAppidTokenConfigIdTokenClaim `pulumi:"idTokenClaims"`
	RefreshTokenEnabled   bool                              `pulumi:"refreshTokenEnabled"`
	RefreshTokenExpiresIn int                               `pulumi:"refreshTokenExpiresIn"`
	TenantId              string                            `pulumi:"tenantId"`
}

func LookupAppidTokenConfigOutput(ctx *pulumi.Context, args LookupAppidTokenConfigOutputArgs, opts ...pulumi.InvokeOption) LookupAppidTokenConfigResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupAppidTokenConfigResultOutput, error) {
			args := v.(LookupAppidTokenConfigArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("ibmcloud:index/getAppidTokenConfig:getAppidTokenConfig", args, LookupAppidTokenConfigResultOutput{}, options).(LookupAppidTokenConfigResultOutput), nil
		}).(LookupAppidTokenConfigResultOutput)
}

// A collection of arguments for invoking getAppidTokenConfig.
type LookupAppidTokenConfigOutputArgs struct {
	TenantId pulumi.StringInput `pulumi:"tenantId"`
}

func (LookupAppidTokenConfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAppidTokenConfigArgs)(nil)).Elem()
}

// A collection of values returned by getAppidTokenConfig.
type LookupAppidTokenConfigResultOutput struct{ *pulumi.OutputState }

func (LookupAppidTokenConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAppidTokenConfigResult)(nil)).Elem()
}

func (o LookupAppidTokenConfigResultOutput) ToLookupAppidTokenConfigResultOutput() LookupAppidTokenConfigResultOutput {
	return o
}

func (o LookupAppidTokenConfigResultOutput) ToLookupAppidTokenConfigResultOutputWithContext(ctx context.Context) LookupAppidTokenConfigResultOutput {
	return o
}

func (o LookupAppidTokenConfigResultOutput) AccessTokenClaims() GetAppidTokenConfigAccessTokenClaimArrayOutput {
	return o.ApplyT(func(v LookupAppidTokenConfigResult) []GetAppidTokenConfigAccessTokenClaim { return v.AccessTokenClaims }).(GetAppidTokenConfigAccessTokenClaimArrayOutput)
}

func (o LookupAppidTokenConfigResultOutput) AccessTokenExpiresIn() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAppidTokenConfigResult) int { return v.AccessTokenExpiresIn }).(pulumi.IntOutput)
}

func (o LookupAppidTokenConfigResultOutput) AnonymousAccessEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAppidTokenConfigResult) bool { return v.AnonymousAccessEnabled }).(pulumi.BoolOutput)
}

func (o LookupAppidTokenConfigResultOutput) AnonymousTokenExpiresIn() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAppidTokenConfigResult) int { return v.AnonymousTokenExpiresIn }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupAppidTokenConfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppidTokenConfigResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupAppidTokenConfigResultOutput) IdTokenClaims() GetAppidTokenConfigIdTokenClaimArrayOutput {
	return o.ApplyT(func(v LookupAppidTokenConfigResult) []GetAppidTokenConfigIdTokenClaim { return v.IdTokenClaims }).(GetAppidTokenConfigIdTokenClaimArrayOutput)
}

func (o LookupAppidTokenConfigResultOutput) RefreshTokenEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAppidTokenConfigResult) bool { return v.RefreshTokenEnabled }).(pulumi.BoolOutput)
}

func (o LookupAppidTokenConfigResultOutput) RefreshTokenExpiresIn() pulumi.IntOutput {
	return o.ApplyT(func(v LookupAppidTokenConfigResult) int { return v.RefreshTokenExpiresIn }).(pulumi.IntOutput)
}

func (o LookupAppidTokenConfigResultOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppidTokenConfigResult) string { return v.TenantId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAppidTokenConfigResultOutput{})
}
