// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ibmcloud

import (
	"context"
	"reflect"

	"github.com/mapt-oss/pulumi-ibmcloud/sdk/go/ibmcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCloudShellAccountSettings(ctx *pulumi.Context, args *LookupCloudShellAccountSettingsArgs, opts ...pulumi.InvokeOption) (*LookupCloudShellAccountSettingsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupCloudShellAccountSettingsResult
	err := ctx.Invoke("ibmcloud:index/getCloudShellAccountSettings:getCloudShellAccountSettings", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudShellAccountSettings.
type LookupCloudShellAccountSettingsArgs struct {
	AccountId string `pulumi:"accountId"`
}

// A collection of values returned by getCloudShellAccountSettings.
type LookupCloudShellAccountSettingsResult struct {
	AccountId                string                                `pulumi:"accountId"`
	CreatedAt                int                                   `pulumi:"createdAt"`
	CreatedBy                string                                `pulumi:"createdBy"`
	DefaultEnableNewFeatures bool                                  `pulumi:"defaultEnableNewFeatures"`
	DefaultEnableNewRegions  bool                                  `pulumi:"defaultEnableNewRegions"`
	Enabled                  bool                                  `pulumi:"enabled"`
	Features                 []GetCloudShellAccountSettingsFeature `pulumi:"features"`
	// The provider-assigned unique ID for this managed resource.
	Id        string                               `pulumi:"id"`
	Regions   []GetCloudShellAccountSettingsRegion `pulumi:"regions"`
	Rev       string                               `pulumi:"rev"`
	Type      string                               `pulumi:"type"`
	UpdatedAt int                                  `pulumi:"updatedAt"`
	UpdatedBy string                               `pulumi:"updatedBy"`
}

func LookupCloudShellAccountSettingsOutput(ctx *pulumi.Context, args LookupCloudShellAccountSettingsOutputArgs, opts ...pulumi.InvokeOption) LookupCloudShellAccountSettingsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupCloudShellAccountSettingsResultOutput, error) {
			args := v.(LookupCloudShellAccountSettingsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("ibmcloud:index/getCloudShellAccountSettings:getCloudShellAccountSettings", args, LookupCloudShellAccountSettingsResultOutput{}, options).(LookupCloudShellAccountSettingsResultOutput), nil
		}).(LookupCloudShellAccountSettingsResultOutput)
}

// A collection of arguments for invoking getCloudShellAccountSettings.
type LookupCloudShellAccountSettingsOutputArgs struct {
	AccountId pulumi.StringInput `pulumi:"accountId"`
}

func (LookupCloudShellAccountSettingsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudShellAccountSettingsArgs)(nil)).Elem()
}

// A collection of values returned by getCloudShellAccountSettings.
type LookupCloudShellAccountSettingsResultOutput struct{ *pulumi.OutputState }

func (LookupCloudShellAccountSettingsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudShellAccountSettingsResult)(nil)).Elem()
}

func (o LookupCloudShellAccountSettingsResultOutput) ToLookupCloudShellAccountSettingsResultOutput() LookupCloudShellAccountSettingsResultOutput {
	return o
}

func (o LookupCloudShellAccountSettingsResultOutput) ToLookupCloudShellAccountSettingsResultOutputWithContext(ctx context.Context) LookupCloudShellAccountSettingsResultOutput {
	return o
}

func (o LookupCloudShellAccountSettingsResultOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) string { return v.AccountId }).(pulumi.StringOutput)
}

func (o LookupCloudShellAccountSettingsResultOutput) CreatedAt() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) int { return v.CreatedAt }).(pulumi.IntOutput)
}

func (o LookupCloudShellAccountSettingsResultOutput) CreatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) string { return v.CreatedBy }).(pulumi.StringOutput)
}

func (o LookupCloudShellAccountSettingsResultOutput) DefaultEnableNewFeatures() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) bool { return v.DefaultEnableNewFeatures }).(pulumi.BoolOutput)
}

func (o LookupCloudShellAccountSettingsResultOutput) DefaultEnableNewRegions() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) bool { return v.DefaultEnableNewRegions }).(pulumi.BoolOutput)
}

func (o LookupCloudShellAccountSettingsResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

func (o LookupCloudShellAccountSettingsResultOutput) Features() GetCloudShellAccountSettingsFeatureArrayOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) []GetCloudShellAccountSettingsFeature { return v.Features }).(GetCloudShellAccountSettingsFeatureArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupCloudShellAccountSettingsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupCloudShellAccountSettingsResultOutput) Regions() GetCloudShellAccountSettingsRegionArrayOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) []GetCloudShellAccountSettingsRegion { return v.Regions }).(GetCloudShellAccountSettingsRegionArrayOutput)
}

func (o LookupCloudShellAccountSettingsResultOutput) Rev() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) string { return v.Rev }).(pulumi.StringOutput)
}

func (o LookupCloudShellAccountSettingsResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) string { return v.Type }).(pulumi.StringOutput)
}

func (o LookupCloudShellAccountSettingsResultOutput) UpdatedAt() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) int { return v.UpdatedAt }).(pulumi.IntOutput)
}

func (o LookupCloudShellAccountSettingsResultOutput) UpdatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudShellAccountSettingsResult) string { return v.UpdatedBy }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCloudShellAccountSettingsResultOutput{})
}
