// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ibmcloud

import (
	"context"
	"reflect"

	"github.com/mapt-oss/pulumi-ibmcloud/sdk/go/ibmcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetEnEmailTemplates(ctx *pulumi.Context, args *GetEnEmailTemplatesArgs, opts ...pulumi.InvokeOption) (*GetEnEmailTemplatesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetEnEmailTemplatesResult
	err := ctx.Invoke("ibmcloud:index/getEnEmailTemplates:getEnEmailTemplates", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getEnEmailTemplates.
type GetEnEmailTemplatesArgs struct {
	InstanceGuid string  `pulumi:"instanceGuid"`
	SearchKey    *string `pulumi:"searchKey"`
}

// A collection of values returned by getEnEmailTemplates.
type GetEnEmailTemplatesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id           string                        `pulumi:"id"`
	InstanceGuid string                        `pulumi:"instanceGuid"`
	SearchKey    *string                       `pulumi:"searchKey"`
	Templates    []GetEnEmailTemplatesTemplate `pulumi:"templates"`
	TotalCount   int                           `pulumi:"totalCount"`
}

func GetEnEmailTemplatesOutput(ctx *pulumi.Context, args GetEnEmailTemplatesOutputArgs, opts ...pulumi.InvokeOption) GetEnEmailTemplatesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetEnEmailTemplatesResultOutput, error) {
			args := v.(GetEnEmailTemplatesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("ibmcloud:index/getEnEmailTemplates:getEnEmailTemplates", args, GetEnEmailTemplatesResultOutput{}, options).(GetEnEmailTemplatesResultOutput), nil
		}).(GetEnEmailTemplatesResultOutput)
}

// A collection of arguments for invoking getEnEmailTemplates.
type GetEnEmailTemplatesOutputArgs struct {
	InstanceGuid pulumi.StringInput    `pulumi:"instanceGuid"`
	SearchKey    pulumi.StringPtrInput `pulumi:"searchKey"`
}

func (GetEnEmailTemplatesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEnEmailTemplatesArgs)(nil)).Elem()
}

// A collection of values returned by getEnEmailTemplates.
type GetEnEmailTemplatesResultOutput struct{ *pulumi.OutputState }

func (GetEnEmailTemplatesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEnEmailTemplatesResult)(nil)).Elem()
}

func (o GetEnEmailTemplatesResultOutput) ToGetEnEmailTemplatesResultOutput() GetEnEmailTemplatesResultOutput {
	return o
}

func (o GetEnEmailTemplatesResultOutput) ToGetEnEmailTemplatesResultOutputWithContext(ctx context.Context) GetEnEmailTemplatesResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetEnEmailTemplatesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnEmailTemplatesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetEnEmailTemplatesResultOutput) InstanceGuid() pulumi.StringOutput {
	return o.ApplyT(func(v GetEnEmailTemplatesResult) string { return v.InstanceGuid }).(pulumi.StringOutput)
}

func (o GetEnEmailTemplatesResultOutput) SearchKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetEnEmailTemplatesResult) *string { return v.SearchKey }).(pulumi.StringPtrOutput)
}

func (o GetEnEmailTemplatesResultOutput) Templates() GetEnEmailTemplatesTemplateArrayOutput {
	return o.ApplyT(func(v GetEnEmailTemplatesResult) []GetEnEmailTemplatesTemplate { return v.Templates }).(GetEnEmailTemplatesTemplateArrayOutput)
}

func (o GetEnEmailTemplatesResultOutput) TotalCount() pulumi.IntOutput {
	return o.ApplyT(func(v GetEnEmailTemplatesResult) int { return v.TotalCount }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(GetEnEmailTemplatesResultOutput{})
}
