// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ibmcloud

import (
	"context"
	"reflect"

	"github.com/mapt-oss/pulumi-ibmcloud/sdk/go/ibmcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSatelliteLink(ctx *pulumi.Context, args *LookupSatelliteLinkArgs, opts ...pulumi.InvokeOption) (*LookupSatelliteLinkResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSatelliteLinkResult
	err := ctx.Invoke("ibmcloud:index/getSatelliteLink:getSatelliteLink", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSatelliteLink.
type LookupSatelliteLinkArgs struct {
	Location string `pulumi:"location"`
}

// A collection of values returned by getSatelliteLink.
type LookupSatelliteLinkResult struct {
	CreatedAt   string `pulumi:"createdAt"`
	Crn         string `pulumi:"crn"`
	Description string `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id                string                        `pulumi:"id"`
	LastChange        string                        `pulumi:"lastChange"`
	Location          string                        `pulumi:"location"`
	Performances      []GetSatelliteLinkPerformance `pulumi:"performances"`
	SatelliteLinkHost string                        `pulumi:"satelliteLinkHost"`
	Status            string                        `pulumi:"status"`
	WsEndpoint        string                        `pulumi:"wsEndpoint"`
}

func LookupSatelliteLinkOutput(ctx *pulumi.Context, args LookupSatelliteLinkOutputArgs, opts ...pulumi.InvokeOption) LookupSatelliteLinkResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSatelliteLinkResultOutput, error) {
			args := v.(LookupSatelliteLinkArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("ibmcloud:index/getSatelliteLink:getSatelliteLink", args, LookupSatelliteLinkResultOutput{}, options).(LookupSatelliteLinkResultOutput), nil
		}).(LookupSatelliteLinkResultOutput)
}

// A collection of arguments for invoking getSatelliteLink.
type LookupSatelliteLinkOutputArgs struct {
	Location pulumi.StringInput `pulumi:"location"`
}

func (LookupSatelliteLinkOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSatelliteLinkArgs)(nil)).Elem()
}

// A collection of values returned by getSatelliteLink.
type LookupSatelliteLinkResultOutput struct{ *pulumi.OutputState }

func (LookupSatelliteLinkResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSatelliteLinkResult)(nil)).Elem()
}

func (o LookupSatelliteLinkResultOutput) ToLookupSatelliteLinkResultOutput() LookupSatelliteLinkResultOutput {
	return o
}

func (o LookupSatelliteLinkResultOutput) ToLookupSatelliteLinkResultOutputWithContext(ctx context.Context) LookupSatelliteLinkResultOutput {
	return o
}

func (o LookupSatelliteLinkResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSatelliteLinkResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupSatelliteLinkResultOutput) Crn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSatelliteLinkResult) string { return v.Crn }).(pulumi.StringOutput)
}

func (o LookupSatelliteLinkResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSatelliteLinkResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSatelliteLinkResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSatelliteLinkResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSatelliteLinkResultOutput) LastChange() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSatelliteLinkResult) string { return v.LastChange }).(pulumi.StringOutput)
}

func (o LookupSatelliteLinkResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSatelliteLinkResult) string { return v.Location }).(pulumi.StringOutput)
}

func (o LookupSatelliteLinkResultOutput) Performances() GetSatelliteLinkPerformanceArrayOutput {
	return o.ApplyT(func(v LookupSatelliteLinkResult) []GetSatelliteLinkPerformance { return v.Performances }).(GetSatelliteLinkPerformanceArrayOutput)
}

func (o LookupSatelliteLinkResultOutput) SatelliteLinkHost() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSatelliteLinkResult) string { return v.SatelliteLinkHost }).(pulumi.StringOutput)
}

func (o LookupSatelliteLinkResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSatelliteLinkResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupSatelliteLinkResultOutput) WsEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSatelliteLinkResult) string { return v.WsEndpoint }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSatelliteLinkResultOutput{})
}
