// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ibmcloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/mapt-oss/pulumi-ibmcloud/sdk/go/ibmcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PiVolumeAttach struct {
	pulumi.CustomResourceState

	// The GUID of the service instance associated with an account.
	PiCloudInstanceId pulumi.StringOutput `pulumi:"piCloudInstanceId"`
	// PI Instance Id
	PiInstanceId pulumi.StringOutput `pulumi:"piInstanceId"`
	// Id of the volume to attach. Note these volumes should have been created
	PiVolumeId pulumi.StringOutput `pulumi:"piVolumeId"`
	// The status of the volume.
	Status pulumi.StringOutput `pulumi:"status"`
}

// NewPiVolumeAttach registers a new resource with the given unique name, arguments, and options.
func NewPiVolumeAttach(ctx *pulumi.Context,
	name string, args *PiVolumeAttachArgs, opts ...pulumi.ResourceOption) (*PiVolumeAttach, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PiCloudInstanceId == nil {
		return nil, errors.New("invalid value for required argument 'PiCloudInstanceId'")
	}
	if args.PiInstanceId == nil {
		return nil, errors.New("invalid value for required argument 'PiInstanceId'")
	}
	if args.PiVolumeId == nil {
		return nil, errors.New("invalid value for required argument 'PiVolumeId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PiVolumeAttach
	err := ctx.RegisterResource("ibmcloud:index/piVolumeAttach:PiVolumeAttach", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPiVolumeAttach gets an existing PiVolumeAttach resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPiVolumeAttach(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PiVolumeAttachState, opts ...pulumi.ResourceOption) (*PiVolumeAttach, error) {
	var resource PiVolumeAttach
	err := ctx.ReadResource("ibmcloud:index/piVolumeAttach:PiVolumeAttach", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PiVolumeAttach resources.
type piVolumeAttachState struct {
	// The GUID of the service instance associated with an account.
	PiCloudInstanceId *string `pulumi:"piCloudInstanceId"`
	// PI Instance Id
	PiInstanceId *string `pulumi:"piInstanceId"`
	// Id of the volume to attach. Note these volumes should have been created
	PiVolumeId *string `pulumi:"piVolumeId"`
	// The status of the volume.
	Status *string `pulumi:"status"`
}

type PiVolumeAttachState struct {
	// The GUID of the service instance associated with an account.
	PiCloudInstanceId pulumi.StringPtrInput
	// PI Instance Id
	PiInstanceId pulumi.StringPtrInput
	// Id of the volume to attach. Note these volumes should have been created
	PiVolumeId pulumi.StringPtrInput
	// The status of the volume.
	Status pulumi.StringPtrInput
}

func (PiVolumeAttachState) ElementType() reflect.Type {
	return reflect.TypeOf((*piVolumeAttachState)(nil)).Elem()
}

type piVolumeAttachArgs struct {
	// The GUID of the service instance associated with an account.
	PiCloudInstanceId string `pulumi:"piCloudInstanceId"`
	// PI Instance Id
	PiInstanceId string `pulumi:"piInstanceId"`
	// Id of the volume to attach. Note these volumes should have been created
	PiVolumeId string `pulumi:"piVolumeId"`
}

// The set of arguments for constructing a PiVolumeAttach resource.
type PiVolumeAttachArgs struct {
	// The GUID of the service instance associated with an account.
	PiCloudInstanceId pulumi.StringInput
	// PI Instance Id
	PiInstanceId pulumi.StringInput
	// Id of the volume to attach. Note these volumes should have been created
	PiVolumeId pulumi.StringInput
}

func (PiVolumeAttachArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*piVolumeAttachArgs)(nil)).Elem()
}

type PiVolumeAttachInput interface {
	pulumi.Input

	ToPiVolumeAttachOutput() PiVolumeAttachOutput
	ToPiVolumeAttachOutputWithContext(ctx context.Context) PiVolumeAttachOutput
}

func (*PiVolumeAttach) ElementType() reflect.Type {
	return reflect.TypeOf((**PiVolumeAttach)(nil)).Elem()
}

func (i *PiVolumeAttach) ToPiVolumeAttachOutput() PiVolumeAttachOutput {
	return i.ToPiVolumeAttachOutputWithContext(context.Background())
}

func (i *PiVolumeAttach) ToPiVolumeAttachOutputWithContext(ctx context.Context) PiVolumeAttachOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PiVolumeAttachOutput)
}

// PiVolumeAttachArrayInput is an input type that accepts PiVolumeAttachArray and PiVolumeAttachArrayOutput values.
// You can construct a concrete instance of `PiVolumeAttachArrayInput` via:
//
//	PiVolumeAttachArray{ PiVolumeAttachArgs{...} }
type PiVolumeAttachArrayInput interface {
	pulumi.Input

	ToPiVolumeAttachArrayOutput() PiVolumeAttachArrayOutput
	ToPiVolumeAttachArrayOutputWithContext(context.Context) PiVolumeAttachArrayOutput
}

type PiVolumeAttachArray []PiVolumeAttachInput

func (PiVolumeAttachArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PiVolumeAttach)(nil)).Elem()
}

func (i PiVolumeAttachArray) ToPiVolumeAttachArrayOutput() PiVolumeAttachArrayOutput {
	return i.ToPiVolumeAttachArrayOutputWithContext(context.Background())
}

func (i PiVolumeAttachArray) ToPiVolumeAttachArrayOutputWithContext(ctx context.Context) PiVolumeAttachArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PiVolumeAttachArrayOutput)
}

// PiVolumeAttachMapInput is an input type that accepts PiVolumeAttachMap and PiVolumeAttachMapOutput values.
// You can construct a concrete instance of `PiVolumeAttachMapInput` via:
//
//	PiVolumeAttachMap{ "key": PiVolumeAttachArgs{...} }
type PiVolumeAttachMapInput interface {
	pulumi.Input

	ToPiVolumeAttachMapOutput() PiVolumeAttachMapOutput
	ToPiVolumeAttachMapOutputWithContext(context.Context) PiVolumeAttachMapOutput
}

type PiVolumeAttachMap map[string]PiVolumeAttachInput

func (PiVolumeAttachMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PiVolumeAttach)(nil)).Elem()
}

func (i PiVolumeAttachMap) ToPiVolumeAttachMapOutput() PiVolumeAttachMapOutput {
	return i.ToPiVolumeAttachMapOutputWithContext(context.Background())
}

func (i PiVolumeAttachMap) ToPiVolumeAttachMapOutputWithContext(ctx context.Context) PiVolumeAttachMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PiVolumeAttachMapOutput)
}

type PiVolumeAttachOutput struct{ *pulumi.OutputState }

func (PiVolumeAttachOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PiVolumeAttach)(nil)).Elem()
}

func (o PiVolumeAttachOutput) ToPiVolumeAttachOutput() PiVolumeAttachOutput {
	return o
}

func (o PiVolumeAttachOutput) ToPiVolumeAttachOutputWithContext(ctx context.Context) PiVolumeAttachOutput {
	return o
}

// The GUID of the service instance associated with an account.
func (o PiVolumeAttachOutput) PiCloudInstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v *PiVolumeAttach) pulumi.StringOutput { return v.PiCloudInstanceId }).(pulumi.StringOutput)
}

// PI Instance Id
func (o PiVolumeAttachOutput) PiInstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v *PiVolumeAttach) pulumi.StringOutput { return v.PiInstanceId }).(pulumi.StringOutput)
}

// Id of the volume to attach. Note these volumes should have been created
func (o PiVolumeAttachOutput) PiVolumeId() pulumi.StringOutput {
	return o.ApplyT(func(v *PiVolumeAttach) pulumi.StringOutput { return v.PiVolumeId }).(pulumi.StringOutput)
}

// The status of the volume.
func (o PiVolumeAttachOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *PiVolumeAttach) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

type PiVolumeAttachArrayOutput struct{ *pulumi.OutputState }

func (PiVolumeAttachArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*PiVolumeAttach)(nil)).Elem()
}

func (o PiVolumeAttachArrayOutput) ToPiVolumeAttachArrayOutput() PiVolumeAttachArrayOutput {
	return o
}

func (o PiVolumeAttachArrayOutput) ToPiVolumeAttachArrayOutputWithContext(ctx context.Context) PiVolumeAttachArrayOutput {
	return o
}

func (o PiVolumeAttachArrayOutput) Index(i pulumi.IntInput) PiVolumeAttachOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *PiVolumeAttach {
		return vs[0].([]*PiVolumeAttach)[vs[1].(int)]
	}).(PiVolumeAttachOutput)
}

type PiVolumeAttachMapOutput struct{ *pulumi.OutputState }

func (PiVolumeAttachMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*PiVolumeAttach)(nil)).Elem()
}

func (o PiVolumeAttachMapOutput) ToPiVolumeAttachMapOutput() PiVolumeAttachMapOutput {
	return o
}

func (o PiVolumeAttachMapOutput) ToPiVolumeAttachMapOutputWithContext(ctx context.Context) PiVolumeAttachMapOutput {
	return o
}

func (o PiVolumeAttachMapOutput) MapIndex(k pulumi.StringInput) PiVolumeAttachOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *PiVolumeAttach {
		return vs[0].(map[string]*PiVolumeAttach)[vs[1].(string)]
	}).(PiVolumeAttachOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PiVolumeAttachInput)(nil)).Elem(), &PiVolumeAttach{})
	pulumi.RegisterInputType(reflect.TypeOf((*PiVolumeAttachArrayInput)(nil)).Elem(), PiVolumeAttachArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*PiVolumeAttachMapInput)(nil)).Elem(), PiVolumeAttachMap{})
	pulumi.RegisterOutputType(PiVolumeAttachOutput{})
	pulumi.RegisterOutputType(PiVolumeAttachArrayOutput{})
	pulumi.RegisterOutputType(PiVolumeAttachMapOutput{})
}
