// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ibmcloud

import (
	"context"
	"reflect"

	"errors"
	"github.com/mapt-oss/pulumi-ibmcloud/sdk/go/ibmcloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SmPublicCertificateConfigurationCaLetsEncrypt struct {
	pulumi.CustomResourceState

	// The configuration type.
	ConfigType pulumi.StringOutput `pulumi:"configType"`
	// public or private.
	EndpointType pulumi.StringPtrOutput `pulumi:"endpointType"`
	// The ID of the Secrets Manager instance.
	InstanceId pulumi.StringOutput `pulumi:"instanceId"`
	// The configuration of the Let's Encrypt CA environment.
	LetsEncryptEnvironment pulumi.StringOutput `pulumi:"letsEncryptEnvironment"`
	// Prefer the chain with an issuer matching this Subject Common Name.
	LetsEncryptPreferredChain pulumi.StringPtrOutput `pulumi:"letsEncryptPreferredChain"`
	// The PEM encoded private key of your Lets Encrypt account.
	LetsEncryptPrivateKey pulumi.StringOutput `pulumi:"letsEncryptPrivateKey"`
	// A human-readable unique name to assign to your configuration.To protect your privacy, do not use personal data, such as your name or location, as an name for your secret.
	Name pulumi.StringOutput `pulumi:"name"`
	// The region of the Secrets Manager instance.
	Region pulumi.StringOutput `pulumi:"region"`
	// The secret type. Supported types are arbitrary, certificates (imported, public, and private), IAM credentials, key-value, and user credentials.
	SecretType pulumi.StringOutput `pulumi:"secretType"`
}

// NewSmPublicCertificateConfigurationCaLetsEncrypt registers a new resource with the given unique name, arguments, and options.
func NewSmPublicCertificateConfigurationCaLetsEncrypt(ctx *pulumi.Context,
	name string, args *SmPublicCertificateConfigurationCaLetsEncryptArgs, opts ...pulumi.ResourceOption) (*SmPublicCertificateConfigurationCaLetsEncrypt, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.InstanceId == nil {
		return nil, errors.New("invalid value for required argument 'InstanceId'")
	}
	if args.LetsEncryptEnvironment == nil {
		return nil, errors.New("invalid value for required argument 'LetsEncryptEnvironment'")
	}
	if args.LetsEncryptPrivateKey == nil {
		return nil, errors.New("invalid value for required argument 'LetsEncryptPrivateKey'")
	}
	if args.LetsEncryptPrivateKey != nil {
		args.LetsEncryptPrivateKey = pulumi.ToSecret(args.LetsEncryptPrivateKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"letsEncryptPrivateKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SmPublicCertificateConfigurationCaLetsEncrypt
	err := ctx.RegisterResource("ibmcloud:index/smPublicCertificateConfigurationCaLetsEncrypt:SmPublicCertificateConfigurationCaLetsEncrypt", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSmPublicCertificateConfigurationCaLetsEncrypt gets an existing SmPublicCertificateConfigurationCaLetsEncrypt resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSmPublicCertificateConfigurationCaLetsEncrypt(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SmPublicCertificateConfigurationCaLetsEncryptState, opts ...pulumi.ResourceOption) (*SmPublicCertificateConfigurationCaLetsEncrypt, error) {
	var resource SmPublicCertificateConfigurationCaLetsEncrypt
	err := ctx.ReadResource("ibmcloud:index/smPublicCertificateConfigurationCaLetsEncrypt:SmPublicCertificateConfigurationCaLetsEncrypt", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SmPublicCertificateConfigurationCaLetsEncrypt resources.
type smPublicCertificateConfigurationCaLetsEncryptState struct {
	// The configuration type.
	ConfigType *string `pulumi:"configType"`
	// public or private.
	EndpointType *string `pulumi:"endpointType"`
	// The ID of the Secrets Manager instance.
	InstanceId *string `pulumi:"instanceId"`
	// The configuration of the Let's Encrypt CA environment.
	LetsEncryptEnvironment *string `pulumi:"letsEncryptEnvironment"`
	// Prefer the chain with an issuer matching this Subject Common Name.
	LetsEncryptPreferredChain *string `pulumi:"letsEncryptPreferredChain"`
	// The PEM encoded private key of your Lets Encrypt account.
	LetsEncryptPrivateKey *string `pulumi:"letsEncryptPrivateKey"`
	// A human-readable unique name to assign to your configuration.To protect your privacy, do not use personal data, such as your name or location, as an name for your secret.
	Name *string `pulumi:"name"`
	// The region of the Secrets Manager instance.
	Region *string `pulumi:"region"`
	// The secret type. Supported types are arbitrary, certificates (imported, public, and private), IAM credentials, key-value, and user credentials.
	SecretType *string `pulumi:"secretType"`
}

type SmPublicCertificateConfigurationCaLetsEncryptState struct {
	// The configuration type.
	ConfigType pulumi.StringPtrInput
	// public or private.
	EndpointType pulumi.StringPtrInput
	// The ID of the Secrets Manager instance.
	InstanceId pulumi.StringPtrInput
	// The configuration of the Let's Encrypt CA environment.
	LetsEncryptEnvironment pulumi.StringPtrInput
	// Prefer the chain with an issuer matching this Subject Common Name.
	LetsEncryptPreferredChain pulumi.StringPtrInput
	// The PEM encoded private key of your Lets Encrypt account.
	LetsEncryptPrivateKey pulumi.StringPtrInput
	// A human-readable unique name to assign to your configuration.To protect your privacy, do not use personal data, such as your name or location, as an name for your secret.
	Name pulumi.StringPtrInput
	// The region of the Secrets Manager instance.
	Region pulumi.StringPtrInput
	// The secret type. Supported types are arbitrary, certificates (imported, public, and private), IAM credentials, key-value, and user credentials.
	SecretType pulumi.StringPtrInput
}

func (SmPublicCertificateConfigurationCaLetsEncryptState) ElementType() reflect.Type {
	return reflect.TypeOf((*smPublicCertificateConfigurationCaLetsEncryptState)(nil)).Elem()
}

type smPublicCertificateConfigurationCaLetsEncryptArgs struct {
	// public or private.
	EndpointType *string `pulumi:"endpointType"`
	// The ID of the Secrets Manager instance.
	InstanceId string `pulumi:"instanceId"`
	// The configuration of the Let's Encrypt CA environment.
	LetsEncryptEnvironment string `pulumi:"letsEncryptEnvironment"`
	// Prefer the chain with an issuer matching this Subject Common Name.
	LetsEncryptPreferredChain *string `pulumi:"letsEncryptPreferredChain"`
	// The PEM encoded private key of your Lets Encrypt account.
	LetsEncryptPrivateKey string `pulumi:"letsEncryptPrivateKey"`
	// A human-readable unique name to assign to your configuration.To protect your privacy, do not use personal data, such as your name or location, as an name for your secret.
	Name *string `pulumi:"name"`
	// The region of the Secrets Manager instance.
	Region *string `pulumi:"region"`
}

// The set of arguments for constructing a SmPublicCertificateConfigurationCaLetsEncrypt resource.
type SmPublicCertificateConfigurationCaLetsEncryptArgs struct {
	// public or private.
	EndpointType pulumi.StringPtrInput
	// The ID of the Secrets Manager instance.
	InstanceId pulumi.StringInput
	// The configuration of the Let's Encrypt CA environment.
	LetsEncryptEnvironment pulumi.StringInput
	// Prefer the chain with an issuer matching this Subject Common Name.
	LetsEncryptPreferredChain pulumi.StringPtrInput
	// The PEM encoded private key of your Lets Encrypt account.
	LetsEncryptPrivateKey pulumi.StringInput
	// A human-readable unique name to assign to your configuration.To protect your privacy, do not use personal data, such as your name or location, as an name for your secret.
	Name pulumi.StringPtrInput
	// The region of the Secrets Manager instance.
	Region pulumi.StringPtrInput
}

func (SmPublicCertificateConfigurationCaLetsEncryptArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*smPublicCertificateConfigurationCaLetsEncryptArgs)(nil)).Elem()
}

type SmPublicCertificateConfigurationCaLetsEncryptInput interface {
	pulumi.Input

	ToSmPublicCertificateConfigurationCaLetsEncryptOutput() SmPublicCertificateConfigurationCaLetsEncryptOutput
	ToSmPublicCertificateConfigurationCaLetsEncryptOutputWithContext(ctx context.Context) SmPublicCertificateConfigurationCaLetsEncryptOutput
}

func (*SmPublicCertificateConfigurationCaLetsEncrypt) ElementType() reflect.Type {
	return reflect.TypeOf((**SmPublicCertificateConfigurationCaLetsEncrypt)(nil)).Elem()
}

func (i *SmPublicCertificateConfigurationCaLetsEncrypt) ToSmPublicCertificateConfigurationCaLetsEncryptOutput() SmPublicCertificateConfigurationCaLetsEncryptOutput {
	return i.ToSmPublicCertificateConfigurationCaLetsEncryptOutputWithContext(context.Background())
}

func (i *SmPublicCertificateConfigurationCaLetsEncrypt) ToSmPublicCertificateConfigurationCaLetsEncryptOutputWithContext(ctx context.Context) SmPublicCertificateConfigurationCaLetsEncryptOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmPublicCertificateConfigurationCaLetsEncryptOutput)
}

// SmPublicCertificateConfigurationCaLetsEncryptArrayInput is an input type that accepts SmPublicCertificateConfigurationCaLetsEncryptArray and SmPublicCertificateConfigurationCaLetsEncryptArrayOutput values.
// You can construct a concrete instance of `SmPublicCertificateConfigurationCaLetsEncryptArrayInput` via:
//
//	SmPublicCertificateConfigurationCaLetsEncryptArray{ SmPublicCertificateConfigurationCaLetsEncryptArgs{...} }
type SmPublicCertificateConfigurationCaLetsEncryptArrayInput interface {
	pulumi.Input

	ToSmPublicCertificateConfigurationCaLetsEncryptArrayOutput() SmPublicCertificateConfigurationCaLetsEncryptArrayOutput
	ToSmPublicCertificateConfigurationCaLetsEncryptArrayOutputWithContext(context.Context) SmPublicCertificateConfigurationCaLetsEncryptArrayOutput
}

type SmPublicCertificateConfigurationCaLetsEncryptArray []SmPublicCertificateConfigurationCaLetsEncryptInput

func (SmPublicCertificateConfigurationCaLetsEncryptArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SmPublicCertificateConfigurationCaLetsEncrypt)(nil)).Elem()
}

func (i SmPublicCertificateConfigurationCaLetsEncryptArray) ToSmPublicCertificateConfigurationCaLetsEncryptArrayOutput() SmPublicCertificateConfigurationCaLetsEncryptArrayOutput {
	return i.ToSmPublicCertificateConfigurationCaLetsEncryptArrayOutputWithContext(context.Background())
}

func (i SmPublicCertificateConfigurationCaLetsEncryptArray) ToSmPublicCertificateConfigurationCaLetsEncryptArrayOutputWithContext(ctx context.Context) SmPublicCertificateConfigurationCaLetsEncryptArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmPublicCertificateConfigurationCaLetsEncryptArrayOutput)
}

// SmPublicCertificateConfigurationCaLetsEncryptMapInput is an input type that accepts SmPublicCertificateConfigurationCaLetsEncryptMap and SmPublicCertificateConfigurationCaLetsEncryptMapOutput values.
// You can construct a concrete instance of `SmPublicCertificateConfigurationCaLetsEncryptMapInput` via:
//
//	SmPublicCertificateConfigurationCaLetsEncryptMap{ "key": SmPublicCertificateConfigurationCaLetsEncryptArgs{...} }
type SmPublicCertificateConfigurationCaLetsEncryptMapInput interface {
	pulumi.Input

	ToSmPublicCertificateConfigurationCaLetsEncryptMapOutput() SmPublicCertificateConfigurationCaLetsEncryptMapOutput
	ToSmPublicCertificateConfigurationCaLetsEncryptMapOutputWithContext(context.Context) SmPublicCertificateConfigurationCaLetsEncryptMapOutput
}

type SmPublicCertificateConfigurationCaLetsEncryptMap map[string]SmPublicCertificateConfigurationCaLetsEncryptInput

func (SmPublicCertificateConfigurationCaLetsEncryptMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SmPublicCertificateConfigurationCaLetsEncrypt)(nil)).Elem()
}

func (i SmPublicCertificateConfigurationCaLetsEncryptMap) ToSmPublicCertificateConfigurationCaLetsEncryptMapOutput() SmPublicCertificateConfigurationCaLetsEncryptMapOutput {
	return i.ToSmPublicCertificateConfigurationCaLetsEncryptMapOutputWithContext(context.Background())
}

func (i SmPublicCertificateConfigurationCaLetsEncryptMap) ToSmPublicCertificateConfigurationCaLetsEncryptMapOutputWithContext(ctx context.Context) SmPublicCertificateConfigurationCaLetsEncryptMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmPublicCertificateConfigurationCaLetsEncryptMapOutput)
}

type SmPublicCertificateConfigurationCaLetsEncryptOutput struct{ *pulumi.OutputState }

func (SmPublicCertificateConfigurationCaLetsEncryptOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SmPublicCertificateConfigurationCaLetsEncrypt)(nil)).Elem()
}

func (o SmPublicCertificateConfigurationCaLetsEncryptOutput) ToSmPublicCertificateConfigurationCaLetsEncryptOutput() SmPublicCertificateConfigurationCaLetsEncryptOutput {
	return o
}

func (o SmPublicCertificateConfigurationCaLetsEncryptOutput) ToSmPublicCertificateConfigurationCaLetsEncryptOutputWithContext(ctx context.Context) SmPublicCertificateConfigurationCaLetsEncryptOutput {
	return o
}

// The configuration type.
func (o SmPublicCertificateConfigurationCaLetsEncryptOutput) ConfigType() pulumi.StringOutput {
	return o.ApplyT(func(v *SmPublicCertificateConfigurationCaLetsEncrypt) pulumi.StringOutput { return v.ConfigType }).(pulumi.StringOutput)
}

// public or private.
func (o SmPublicCertificateConfigurationCaLetsEncryptOutput) EndpointType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmPublicCertificateConfigurationCaLetsEncrypt) pulumi.StringPtrOutput { return v.EndpointType }).(pulumi.StringPtrOutput)
}

// The ID of the Secrets Manager instance.
func (o SmPublicCertificateConfigurationCaLetsEncryptOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v *SmPublicCertificateConfigurationCaLetsEncrypt) pulumi.StringOutput { return v.InstanceId }).(pulumi.StringOutput)
}

// The configuration of the Let's Encrypt CA environment.
func (o SmPublicCertificateConfigurationCaLetsEncryptOutput) LetsEncryptEnvironment() pulumi.StringOutput {
	return o.ApplyT(func(v *SmPublicCertificateConfigurationCaLetsEncrypt) pulumi.StringOutput {
		return v.LetsEncryptEnvironment
	}).(pulumi.StringOutput)
}

// Prefer the chain with an issuer matching this Subject Common Name.
func (o SmPublicCertificateConfigurationCaLetsEncryptOutput) LetsEncryptPreferredChain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmPublicCertificateConfigurationCaLetsEncrypt) pulumi.StringPtrOutput {
		return v.LetsEncryptPreferredChain
	}).(pulumi.StringPtrOutput)
}

// The PEM encoded private key of your Lets Encrypt account.
func (o SmPublicCertificateConfigurationCaLetsEncryptOutput) LetsEncryptPrivateKey() pulumi.StringOutput {
	return o.ApplyT(func(v *SmPublicCertificateConfigurationCaLetsEncrypt) pulumi.StringOutput {
		return v.LetsEncryptPrivateKey
	}).(pulumi.StringOutput)
}

// A human-readable unique name to assign to your configuration.To protect your privacy, do not use personal data, such as your name or location, as an name for your secret.
func (o SmPublicCertificateConfigurationCaLetsEncryptOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SmPublicCertificateConfigurationCaLetsEncrypt) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The region of the Secrets Manager instance.
func (o SmPublicCertificateConfigurationCaLetsEncryptOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *SmPublicCertificateConfigurationCaLetsEncrypt) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// The secret type. Supported types are arbitrary, certificates (imported, public, and private), IAM credentials, key-value, and user credentials.
func (o SmPublicCertificateConfigurationCaLetsEncryptOutput) SecretType() pulumi.StringOutput {
	return o.ApplyT(func(v *SmPublicCertificateConfigurationCaLetsEncrypt) pulumi.StringOutput { return v.SecretType }).(pulumi.StringOutput)
}

type SmPublicCertificateConfigurationCaLetsEncryptArrayOutput struct{ *pulumi.OutputState }

func (SmPublicCertificateConfigurationCaLetsEncryptArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SmPublicCertificateConfigurationCaLetsEncrypt)(nil)).Elem()
}

func (o SmPublicCertificateConfigurationCaLetsEncryptArrayOutput) ToSmPublicCertificateConfigurationCaLetsEncryptArrayOutput() SmPublicCertificateConfigurationCaLetsEncryptArrayOutput {
	return o
}

func (o SmPublicCertificateConfigurationCaLetsEncryptArrayOutput) ToSmPublicCertificateConfigurationCaLetsEncryptArrayOutputWithContext(ctx context.Context) SmPublicCertificateConfigurationCaLetsEncryptArrayOutput {
	return o
}

func (o SmPublicCertificateConfigurationCaLetsEncryptArrayOutput) Index(i pulumi.IntInput) SmPublicCertificateConfigurationCaLetsEncryptOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SmPublicCertificateConfigurationCaLetsEncrypt {
		return vs[0].([]*SmPublicCertificateConfigurationCaLetsEncrypt)[vs[1].(int)]
	}).(SmPublicCertificateConfigurationCaLetsEncryptOutput)
}

type SmPublicCertificateConfigurationCaLetsEncryptMapOutput struct{ *pulumi.OutputState }

func (SmPublicCertificateConfigurationCaLetsEncryptMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SmPublicCertificateConfigurationCaLetsEncrypt)(nil)).Elem()
}

func (o SmPublicCertificateConfigurationCaLetsEncryptMapOutput) ToSmPublicCertificateConfigurationCaLetsEncryptMapOutput() SmPublicCertificateConfigurationCaLetsEncryptMapOutput {
	return o
}

func (o SmPublicCertificateConfigurationCaLetsEncryptMapOutput) ToSmPublicCertificateConfigurationCaLetsEncryptMapOutputWithContext(ctx context.Context) SmPublicCertificateConfigurationCaLetsEncryptMapOutput {
	return o
}

func (o SmPublicCertificateConfigurationCaLetsEncryptMapOutput) MapIndex(k pulumi.StringInput) SmPublicCertificateConfigurationCaLetsEncryptOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SmPublicCertificateConfigurationCaLetsEncrypt {
		return vs[0].(map[string]*SmPublicCertificateConfigurationCaLetsEncrypt)[vs[1].(string)]
	}).(SmPublicCertificateConfigurationCaLetsEncryptOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SmPublicCertificateConfigurationCaLetsEncryptInput)(nil)).Elem(), &SmPublicCertificateConfigurationCaLetsEncrypt{})
	pulumi.RegisterInputType(reflect.TypeOf((*SmPublicCertificateConfigurationCaLetsEncryptArrayInput)(nil)).Elem(), SmPublicCertificateConfigurationCaLetsEncryptArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SmPublicCertificateConfigurationCaLetsEncryptMapInput)(nil)).Elem(), SmPublicCertificateConfigurationCaLetsEncryptMap{})
	pulumi.RegisterOutputType(SmPublicCertificateConfigurationCaLetsEncryptOutput{})
	pulumi.RegisterOutputType(SmPublicCertificateConfigurationCaLetsEncryptArrayOutput{})
	pulumi.RegisterOutputType(SmPublicCertificateConfigurationCaLetsEncryptMapOutput{})
}
