# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['CisEdgeFunctionsTriggerArgs', 'CisEdgeFunctionsTrigger']

@pulumi.input_type
class CisEdgeFunctionsTriggerArgs:
    def __init__(__self__, *,
                 cis_id: pulumi.Input[_builtins.str],
                 domain_id: pulumi.Input[_builtins.str],
                 pattern_url: pulumi.Input[_builtins.str],
                 action_name: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a CisEdgeFunctionsTrigger resource.
        :param pulumi.Input[_builtins.str] cis_id: CIS Intance CRN
        :param pulumi.Input[_builtins.str] domain_id: CIS Domain ID
        :param pulumi.Input[_builtins.str] pattern_url: Edge function trigger pattern
        :param pulumi.Input[_builtins.str] action_name: Edge function trigger action name
        """
        pulumi.set(__self__, "cis_id", cis_id)
        pulumi.set(__self__, "domain_id", domain_id)
        pulumi.set(__self__, "pattern_url", pattern_url)
        if action_name is not None:
            pulumi.set(__self__, "action_name", action_name)

    @_builtins.property
    @pulumi.getter(name="cisId")
    def cis_id(self) -> pulumi.Input[_builtins.str]:
        """
        CIS Intance CRN
        """
        return pulumi.get(self, "cis_id")

    @cis_id.setter
    def cis_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cis_id", value)

    @_builtins.property
    @pulumi.getter(name="domainId")
    def domain_id(self) -> pulumi.Input[_builtins.str]:
        """
        CIS Domain ID
        """
        return pulumi.get(self, "domain_id")

    @domain_id.setter
    def domain_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "domain_id", value)

    @_builtins.property
    @pulumi.getter(name="patternUrl")
    def pattern_url(self) -> pulumi.Input[_builtins.str]:
        """
        Edge function trigger pattern
        """
        return pulumi.get(self, "pattern_url")

    @pattern_url.setter
    def pattern_url(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "pattern_url", value)

    @_builtins.property
    @pulumi.getter(name="actionName")
    def action_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Edge function trigger action name
        """
        return pulumi.get(self, "action_name")

    @action_name.setter
    def action_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "action_name", value)


@pulumi.input_type
class _CisEdgeFunctionsTriggerState:
    def __init__(__self__, *,
                 action_name: Optional[pulumi.Input[_builtins.str]] = None,
                 cis_id: Optional[pulumi.Input[_builtins.str]] = None,
                 domain_id: Optional[pulumi.Input[_builtins.str]] = None,
                 pattern_url: Optional[pulumi.Input[_builtins.str]] = None,
                 request_limit_fail_open: Optional[pulumi.Input[_builtins.bool]] = None,
                 trigger_id: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering CisEdgeFunctionsTrigger resources.
        :param pulumi.Input[_builtins.str] action_name: Edge function trigger action name
        :param pulumi.Input[_builtins.str] cis_id: CIS Intance CRN
        :param pulumi.Input[_builtins.str] domain_id: CIS Domain ID
        :param pulumi.Input[_builtins.str] pattern_url: Edge function trigger pattern
        :param pulumi.Input[_builtins.bool] request_limit_fail_open: Edge function trigger request limit fail open
        :param pulumi.Input[_builtins.str] trigger_id: CIS Edge Functions trigger route ID
        """
        if action_name is not None:
            pulumi.set(__self__, "action_name", action_name)
        if cis_id is not None:
            pulumi.set(__self__, "cis_id", cis_id)
        if domain_id is not None:
            pulumi.set(__self__, "domain_id", domain_id)
        if pattern_url is not None:
            pulumi.set(__self__, "pattern_url", pattern_url)
        if request_limit_fail_open is not None:
            pulumi.set(__self__, "request_limit_fail_open", request_limit_fail_open)
        if trigger_id is not None:
            pulumi.set(__self__, "trigger_id", trigger_id)

    @_builtins.property
    @pulumi.getter(name="actionName")
    def action_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Edge function trigger action name
        """
        return pulumi.get(self, "action_name")

    @action_name.setter
    def action_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "action_name", value)

    @_builtins.property
    @pulumi.getter(name="cisId")
    def cis_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        CIS Intance CRN
        """
        return pulumi.get(self, "cis_id")

    @cis_id.setter
    def cis_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cis_id", value)

    @_builtins.property
    @pulumi.getter(name="domainId")
    def domain_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        CIS Domain ID
        """
        return pulumi.get(self, "domain_id")

    @domain_id.setter
    def domain_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "domain_id", value)

    @_builtins.property
    @pulumi.getter(name="patternUrl")
    def pattern_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Edge function trigger pattern
        """
        return pulumi.get(self, "pattern_url")

    @pattern_url.setter
    def pattern_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "pattern_url", value)

    @_builtins.property
    @pulumi.getter(name="requestLimitFailOpen")
    def request_limit_fail_open(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Edge function trigger request limit fail open
        """
        return pulumi.get(self, "request_limit_fail_open")

    @request_limit_fail_open.setter
    def request_limit_fail_open(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "request_limit_fail_open", value)

    @_builtins.property
    @pulumi.getter(name="triggerId")
    def trigger_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        CIS Edge Functions trigger route ID
        """
        return pulumi.get(self, "trigger_id")

    @trigger_id.setter
    def trigger_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "trigger_id", value)


@pulumi.type_token("ibmcloud:index/cisEdgeFunctionsTrigger:CisEdgeFunctionsTrigger")
class CisEdgeFunctionsTrigger(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action_name: Optional[pulumi.Input[_builtins.str]] = None,
                 cis_id: Optional[pulumi.Input[_builtins.str]] = None,
                 domain_id: Optional[pulumi.Input[_builtins.str]] = None,
                 pattern_url: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a CisEdgeFunctionsTrigger resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] action_name: Edge function trigger action name
        :param pulumi.Input[_builtins.str] cis_id: CIS Intance CRN
        :param pulumi.Input[_builtins.str] domain_id: CIS Domain ID
        :param pulumi.Input[_builtins.str] pattern_url: Edge function trigger pattern
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CisEdgeFunctionsTriggerArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a CisEdgeFunctionsTrigger resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param CisEdgeFunctionsTriggerArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CisEdgeFunctionsTriggerArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action_name: Optional[pulumi.Input[_builtins.str]] = None,
                 cis_id: Optional[pulumi.Input[_builtins.str]] = None,
                 domain_id: Optional[pulumi.Input[_builtins.str]] = None,
                 pattern_url: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CisEdgeFunctionsTriggerArgs.__new__(CisEdgeFunctionsTriggerArgs)

            __props__.__dict__["action_name"] = action_name
            if cis_id is None and not opts.urn:
                raise TypeError("Missing required property 'cis_id'")
            __props__.__dict__["cis_id"] = cis_id
            if domain_id is None and not opts.urn:
                raise TypeError("Missing required property 'domain_id'")
            __props__.__dict__["domain_id"] = domain_id
            if pattern_url is None and not opts.urn:
                raise TypeError("Missing required property 'pattern_url'")
            __props__.__dict__["pattern_url"] = pattern_url
            __props__.__dict__["request_limit_fail_open"] = None
            __props__.__dict__["trigger_id"] = None
        super(CisEdgeFunctionsTrigger, __self__).__init__(
            'ibmcloud:index/cisEdgeFunctionsTrigger:CisEdgeFunctionsTrigger',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            action_name: Optional[pulumi.Input[_builtins.str]] = None,
            cis_id: Optional[pulumi.Input[_builtins.str]] = None,
            domain_id: Optional[pulumi.Input[_builtins.str]] = None,
            pattern_url: Optional[pulumi.Input[_builtins.str]] = None,
            request_limit_fail_open: Optional[pulumi.Input[_builtins.bool]] = None,
            trigger_id: Optional[pulumi.Input[_builtins.str]] = None) -> 'CisEdgeFunctionsTrigger':
        """
        Get an existing CisEdgeFunctionsTrigger resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] action_name: Edge function trigger action name
        :param pulumi.Input[_builtins.str] cis_id: CIS Intance CRN
        :param pulumi.Input[_builtins.str] domain_id: CIS Domain ID
        :param pulumi.Input[_builtins.str] pattern_url: Edge function trigger pattern
        :param pulumi.Input[_builtins.bool] request_limit_fail_open: Edge function trigger request limit fail open
        :param pulumi.Input[_builtins.str] trigger_id: CIS Edge Functions trigger route ID
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _CisEdgeFunctionsTriggerState.__new__(_CisEdgeFunctionsTriggerState)

        __props__.__dict__["action_name"] = action_name
        __props__.__dict__["cis_id"] = cis_id
        __props__.__dict__["domain_id"] = domain_id
        __props__.__dict__["pattern_url"] = pattern_url
        __props__.__dict__["request_limit_fail_open"] = request_limit_fail_open
        __props__.__dict__["trigger_id"] = trigger_id
        return CisEdgeFunctionsTrigger(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="actionName")
    def action_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Edge function trigger action name
        """
        return pulumi.get(self, "action_name")

    @_builtins.property
    @pulumi.getter(name="cisId")
    def cis_id(self) -> pulumi.Output[_builtins.str]:
        """
        CIS Intance CRN
        """
        return pulumi.get(self, "cis_id")

    @_builtins.property
    @pulumi.getter(name="domainId")
    def domain_id(self) -> pulumi.Output[_builtins.str]:
        """
        CIS Domain ID
        """
        return pulumi.get(self, "domain_id")

    @_builtins.property
    @pulumi.getter(name="patternUrl")
    def pattern_url(self) -> pulumi.Output[_builtins.str]:
        """
        Edge function trigger pattern
        """
        return pulumi.get(self, "pattern_url")

    @_builtins.property
    @pulumi.getter(name="requestLimitFailOpen")
    def request_limit_fail_open(self) -> pulumi.Output[_builtins.bool]:
        """
        Edge function trigger request limit fail open
        """
        return pulumi.get(self, "request_limit_fail_open")

    @_builtins.property
    @pulumi.getter(name="triggerId")
    def trigger_id(self) -> pulumi.Output[_builtins.str]:
        """
        CIS Edge Functions trigger route ID
        """
        return pulumi.get(self, "trigger_id")

