# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetTgRouteReportsResult',
    'AwaitableGetTgRouteReportsResult',
    'get_tg_route_reports',
    'get_tg_route_reports_output',
]

@pulumi.output_type
class GetTgRouteReportsResult:
    """
    A collection of values returned by getTgRouteReports.
    """
    def __init__(__self__, gateway=None, id=None, route_reports=None):
        if gateway and not isinstance(gateway, str):
            raise TypeError("Expected argument 'gateway' to be a str")
        pulumi.set(__self__, "gateway", gateway)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if route_reports and not isinstance(route_reports, list):
            raise TypeError("Expected argument 'route_reports' to be a list")
        pulumi.set(__self__, "route_reports", route_reports)

    @_builtins.property
    @pulumi.getter
    def gateway(self) -> _builtins.str:
        return pulumi.get(self, "gateway")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="routeReports")
    def route_reports(self) -> Sequence['outputs.GetTgRouteReportsRouteReportResult']:
        return pulumi.get(self, "route_reports")


class AwaitableGetTgRouteReportsResult(GetTgRouteReportsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetTgRouteReportsResult(
            gateway=self.gateway,
            id=self.id,
            route_reports=self.route_reports)


def get_tg_route_reports(gateway: Optional[_builtins.str] = None,
                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetTgRouteReportsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['gateway'] = gateway
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('ibmcloud:index/getTgRouteReports:getTgRouteReports', __args__, opts=opts, typ=GetTgRouteReportsResult).value

    return AwaitableGetTgRouteReportsResult(
        gateway=pulumi.get(__ret__, 'gateway'),
        id=pulumi.get(__ret__, 'id'),
        route_reports=pulumi.get(__ret__, 'route_reports'))
def get_tg_route_reports_output(gateway: Optional[pulumi.Input[_builtins.str]] = None,
                                opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetTgRouteReportsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['gateway'] = gateway
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('ibmcloud:index/getTgRouteReports:getTgRouteReports', __args__, opts=opts, typ=GetTgRouteReportsResult)
    return __ret__.apply(lambda __response__: GetTgRouteReportsResult(
        gateway=pulumi.get(__response__, 'gateway'),
        id=pulumi.get(__response__, 'id'),
        route_reports=pulumi.get(__response__, 'route_reports')))
