# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetPiInstanceNetworksResult',
    'AwaitableGetPiInstanceNetworksResult',
    'get_pi_instance_networks',
    'get_pi_instance_networks_output',
]

@pulumi.output_type
class GetPiInstanceNetworksResult:
    """
    A collection of values returned by getPiInstanceNetworks.
    """
    def __init__(__self__, id=None, networks=None, pi_cloud_instance_id=None, pi_instance_id=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if networks and not isinstance(networks, list):
            raise TypeError("Expected argument 'networks' to be a list")
        pulumi.set(__self__, "networks", networks)
        if pi_cloud_instance_id and not isinstance(pi_cloud_instance_id, str):
            raise TypeError("Expected argument 'pi_cloud_instance_id' to be a str")
        pulumi.set(__self__, "pi_cloud_instance_id", pi_cloud_instance_id)
        if pi_instance_id and not isinstance(pi_instance_id, str):
            raise TypeError("Expected argument 'pi_instance_id' to be a str")
        pulumi.set(__self__, "pi_instance_id", pi_instance_id)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def networks(self) -> Sequence['outputs.GetPiInstanceNetworksNetworkResult']:
        return pulumi.get(self, "networks")

    @_builtins.property
    @pulumi.getter(name="piCloudInstanceId")
    def pi_cloud_instance_id(self) -> _builtins.str:
        return pulumi.get(self, "pi_cloud_instance_id")

    @_builtins.property
    @pulumi.getter(name="piInstanceId")
    def pi_instance_id(self) -> _builtins.str:
        return pulumi.get(self, "pi_instance_id")


class AwaitableGetPiInstanceNetworksResult(GetPiInstanceNetworksResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPiInstanceNetworksResult(
            id=self.id,
            networks=self.networks,
            pi_cloud_instance_id=self.pi_cloud_instance_id,
            pi_instance_id=self.pi_instance_id)


def get_pi_instance_networks(pi_cloud_instance_id: Optional[_builtins.str] = None,
                             pi_instance_id: Optional[_builtins.str] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPiInstanceNetworksResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['piCloudInstanceId'] = pi_cloud_instance_id
    __args__['piInstanceId'] = pi_instance_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('ibmcloud:index/getPiInstanceNetworks:getPiInstanceNetworks', __args__, opts=opts, typ=GetPiInstanceNetworksResult).value

    return AwaitableGetPiInstanceNetworksResult(
        id=pulumi.get(__ret__, 'id'),
        networks=pulumi.get(__ret__, 'networks'),
        pi_cloud_instance_id=pulumi.get(__ret__, 'pi_cloud_instance_id'),
        pi_instance_id=pulumi.get(__ret__, 'pi_instance_id'))
def get_pi_instance_networks_output(pi_cloud_instance_id: pulumi.Input[Optional[_builtins.str]] = None,
                                    pi_instance_id: pulumi.Input[Optional[_builtins.str]] = None,
                                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPiInstanceNetworksResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['piCloudInstanceId'] = pi_cloud_instance_id
    __args__['piInstanceId'] = pi_instance_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('ibmcloud:index/getPiInstanceNetworks:getPiInstanceNetworks', __args__, opts=opts, typ=GetPiInstanceNetworksResult)
    return __ret__.apply(lambda __response__: GetPiInstanceNetworksResult(
        id=pulumi.get(__response__, 'id'),
        networks=pulumi.get(__response__, 'networks'),
        pi_cloud_instance_id=pulumi.get(__response__, 'pi_cloud_instance_id'),
        pi_instance_id=pulumi.get(__response__, 'pi_instance_id')))
