# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetIsDedicatedHostDiskResult',
    'AwaitableGetIsDedicatedHostDiskResult',
    'get_is_dedicated_host_disk',
    'get_is_dedicated_host_disk_output',
]

@pulumi.output_type
class GetIsDedicatedHostDiskResult:
    """
    A collection of values returned by getIsDedicatedHostDisk.
    """
    def __init__(__self__, available=None, created_at=None, dedicated_host=None, disk=None, href=None, id=None, instance_disks=None, interface_type=None, lifecycle_state=None, name=None, provisionable=None, resource_type=None, size=None, supported_instance_interface_types=None):
        if available and not isinstance(available, int):
            raise TypeError("Expected argument 'available' to be a int")
        pulumi.set(__self__, "available", available)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if dedicated_host and not isinstance(dedicated_host, str):
            raise TypeError("Expected argument 'dedicated_host' to be a str")
        pulumi.set(__self__, "dedicated_host", dedicated_host)
        if disk and not isinstance(disk, str):
            raise TypeError("Expected argument 'disk' to be a str")
        pulumi.set(__self__, "disk", disk)
        if href and not isinstance(href, str):
            raise TypeError("Expected argument 'href' to be a str")
        pulumi.set(__self__, "href", href)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if instance_disks and not isinstance(instance_disks, list):
            raise TypeError("Expected argument 'instance_disks' to be a list")
        pulumi.set(__self__, "instance_disks", instance_disks)
        if interface_type and not isinstance(interface_type, str):
            raise TypeError("Expected argument 'interface_type' to be a str")
        pulumi.set(__self__, "interface_type", interface_type)
        if lifecycle_state and not isinstance(lifecycle_state, str):
            raise TypeError("Expected argument 'lifecycle_state' to be a str")
        pulumi.set(__self__, "lifecycle_state", lifecycle_state)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if provisionable and not isinstance(provisionable, bool):
            raise TypeError("Expected argument 'provisionable' to be a bool")
        pulumi.set(__self__, "provisionable", provisionable)
        if resource_type and not isinstance(resource_type, str):
            raise TypeError("Expected argument 'resource_type' to be a str")
        pulumi.set(__self__, "resource_type", resource_type)
        if size and not isinstance(size, int):
            raise TypeError("Expected argument 'size' to be a int")
        pulumi.set(__self__, "size", size)
        if supported_instance_interface_types and not isinstance(supported_instance_interface_types, list):
            raise TypeError("Expected argument 'supported_instance_interface_types' to be a list")
        pulumi.set(__self__, "supported_instance_interface_types", supported_instance_interface_types)

    @_builtins.property
    @pulumi.getter
    def available(self) -> _builtins.int:
        return pulumi.get(self, "available")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="dedicatedHost")
    def dedicated_host(self) -> _builtins.str:
        return pulumi.get(self, "dedicated_host")

    @_builtins.property
    @pulumi.getter
    def disk(self) -> _builtins.str:
        return pulumi.get(self, "disk")

    @_builtins.property
    @pulumi.getter
    def href(self) -> _builtins.str:
        return pulumi.get(self, "href")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="instanceDisks")
    def instance_disks(self) -> Sequence['outputs.GetIsDedicatedHostDiskInstanceDiskResult']:
        return pulumi.get(self, "instance_disks")

    @_builtins.property
    @pulumi.getter(name="interfaceType")
    def interface_type(self) -> _builtins.str:
        return pulumi.get(self, "interface_type")

    @_builtins.property
    @pulumi.getter(name="lifecycleState")
    def lifecycle_state(self) -> _builtins.str:
        return pulumi.get(self, "lifecycle_state")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def provisionable(self) -> _builtins.bool:
        return pulumi.get(self, "provisionable")

    @_builtins.property
    @pulumi.getter(name="resourceType")
    def resource_type(self) -> _builtins.str:
        return pulumi.get(self, "resource_type")

    @_builtins.property
    @pulumi.getter
    def size(self) -> _builtins.int:
        return pulumi.get(self, "size")

    @_builtins.property
    @pulumi.getter(name="supportedInstanceInterfaceTypes")
    def supported_instance_interface_types(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "supported_instance_interface_types")


class AwaitableGetIsDedicatedHostDiskResult(GetIsDedicatedHostDiskResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetIsDedicatedHostDiskResult(
            available=self.available,
            created_at=self.created_at,
            dedicated_host=self.dedicated_host,
            disk=self.disk,
            href=self.href,
            id=self.id,
            instance_disks=self.instance_disks,
            interface_type=self.interface_type,
            lifecycle_state=self.lifecycle_state,
            name=self.name,
            provisionable=self.provisionable,
            resource_type=self.resource_type,
            size=self.size,
            supported_instance_interface_types=self.supported_instance_interface_types)


def get_is_dedicated_host_disk(dedicated_host: Optional[_builtins.str] = None,
                               disk: Optional[_builtins.str] = None,
                               opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetIsDedicatedHostDiskResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['dedicatedHost'] = dedicated_host
    __args__['disk'] = disk
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('ibmcloud:index/getIsDedicatedHostDisk:getIsDedicatedHostDisk', __args__, opts=opts, typ=GetIsDedicatedHostDiskResult).value

    return AwaitableGetIsDedicatedHostDiskResult(
        available=pulumi.get(__ret__, 'available'),
        created_at=pulumi.get(__ret__, 'created_at'),
        dedicated_host=pulumi.get(__ret__, 'dedicated_host'),
        disk=pulumi.get(__ret__, 'disk'),
        href=pulumi.get(__ret__, 'href'),
        id=pulumi.get(__ret__, 'id'),
        instance_disks=pulumi.get(__ret__, 'instance_disks'),
        interface_type=pulumi.get(__ret__, 'interface_type'),
        lifecycle_state=pulumi.get(__ret__, 'lifecycle_state'),
        name=pulumi.get(__ret__, 'name'),
        provisionable=pulumi.get(__ret__, 'provisionable'),
        resource_type=pulumi.get(__ret__, 'resource_type'),
        size=pulumi.get(__ret__, 'size'),
        supported_instance_interface_types=pulumi.get(__ret__, 'supported_instance_interface_types'))
def get_is_dedicated_host_disk_output(dedicated_host: Optional[pulumi.Input[_builtins.str]] = None,
                                      disk: Optional[pulumi.Input[_builtins.str]] = None,
                                      opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetIsDedicatedHostDiskResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['dedicatedHost'] = dedicated_host
    __args__['disk'] = disk
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('ibmcloud:index/getIsDedicatedHostDisk:getIsDedicatedHostDisk', __args__, opts=opts, typ=GetIsDedicatedHostDiskResult)
    return __ret__.apply(lambda __response__: GetIsDedicatedHostDiskResult(
        available=pulumi.get(__response__, 'available'),
        created_at=pulumi.get(__response__, 'created_at'),
        dedicated_host=pulumi.get(__response__, 'dedicated_host'),
        disk=pulumi.get(__response__, 'disk'),
        href=pulumi.get(__response__, 'href'),
        id=pulumi.get(__response__, 'id'),
        instance_disks=pulumi.get(__response__, 'instance_disks'),
        interface_type=pulumi.get(__response__, 'interface_type'),
        lifecycle_state=pulumi.get(__response__, 'lifecycle_state'),
        name=pulumi.get(__response__, 'name'),
        provisionable=pulumi.get(__response__, 'provisionable'),
        resource_type=pulumi.get(__response__, 'resource_type'),
        size=pulumi.get(__response__, 'size'),
        supported_instance_interface_types=pulumi.get(__response__, 'supported_instance_interface_types')))
