// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class BackupRecoveryConnectorRegistration extends pulumi.CustomResource {
    /**
     * Get an existing BackupRecoveryConnectorRegistration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BackupRecoveryConnectorRegistrationState, opts?: pulumi.CustomResourceOptions): BackupRecoveryConnectorRegistration {
        return new BackupRecoveryConnectorRegistration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ibmcloud:index/backupRecoveryConnectorRegistration:BackupRecoveryConnectorRegistration';

    /**
     * Returns true if the given object is an instance of BackupRecoveryConnectorRegistration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BackupRecoveryConnectorRegistration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BackupRecoveryConnectorRegistration.__pulumiType;
    }

    /**
     * Token required to authenticate to the connector. Token can be obtained using ibmcloud.BackupRecoveryConnectorAccessToken resource
     */
    declare public readonly accessToken: pulumi.Output<string>;
    /**
     * The connector's ID to be used for registration. Two connectors belonging to the same tenant are guaranteed to have different IDs.
     */
    declare public readonly connectorId: pulumi.Output<number | undefined>;
    /**
     * public or private.
     */
    declare public readonly endpointType: pulumi.Output<string | undefined>;
    /**
     * The instnace ID of the Backup Recovery instance.
     */
    declare public readonly instanceId: pulumi.Output<string | undefined>;
    /**
     * The region of the Backup Recovery instance.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * The registration token.
     */
    declare public readonly registrationToken: pulumi.Output<string>;

    /**
     * Create a BackupRecoveryConnectorRegistration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BackupRecoveryConnectorRegistrationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BackupRecoveryConnectorRegistrationArgs | BackupRecoveryConnectorRegistrationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BackupRecoveryConnectorRegistrationState | undefined;
            resourceInputs["accessToken"] = state?.accessToken;
            resourceInputs["connectorId"] = state?.connectorId;
            resourceInputs["endpointType"] = state?.endpointType;
            resourceInputs["instanceId"] = state?.instanceId;
            resourceInputs["region"] = state?.region;
            resourceInputs["registrationToken"] = state?.registrationToken;
        } else {
            const args = argsOrState as BackupRecoveryConnectorRegistrationArgs | undefined;
            if (args?.accessToken === undefined && !opts.urn) {
                throw new Error("Missing required property 'accessToken'");
            }
            if (args?.registrationToken === undefined && !opts.urn) {
                throw new Error("Missing required property 'registrationToken'");
            }
            resourceInputs["accessToken"] = args?.accessToken ? pulumi.secret(args.accessToken) : undefined;
            resourceInputs["connectorId"] = args?.connectorId;
            resourceInputs["endpointType"] = args?.endpointType;
            resourceInputs["instanceId"] = args?.instanceId;
            resourceInputs["region"] = args?.region;
            resourceInputs["registrationToken"] = args?.registrationToken;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["accessToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(BackupRecoveryConnectorRegistration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering BackupRecoveryConnectorRegistration resources.
 */
export interface BackupRecoveryConnectorRegistrationState {
    /**
     * Token required to authenticate to the connector. Token can be obtained using ibmcloud.BackupRecoveryConnectorAccessToken resource
     */
    accessToken?: pulumi.Input<string>;
    /**
     * The connector's ID to be used for registration. Two connectors belonging to the same tenant are guaranteed to have different IDs.
     */
    connectorId?: pulumi.Input<number>;
    /**
     * public or private.
     */
    endpointType?: pulumi.Input<string>;
    /**
     * The instnace ID of the Backup Recovery instance.
     */
    instanceId?: pulumi.Input<string>;
    /**
     * The region of the Backup Recovery instance.
     */
    region?: pulumi.Input<string>;
    /**
     * The registration token.
     */
    registrationToken?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a BackupRecoveryConnectorRegistration resource.
 */
export interface BackupRecoveryConnectorRegistrationArgs {
    /**
     * Token required to authenticate to the connector. Token can be obtained using ibmcloud.BackupRecoveryConnectorAccessToken resource
     */
    accessToken: pulumi.Input<string>;
    /**
     * The connector's ID to be used for registration. Two connectors belonging to the same tenant are guaranteed to have different IDs.
     */
    connectorId?: pulumi.Input<number>;
    /**
     * public or private.
     */
    endpointType?: pulumi.Input<string>;
    /**
     * The instnace ID of the Backup Recovery instance.
     */
    instanceId?: pulumi.Input<string>;
    /**
     * The region of the Backup Recovery instance.
     */
    region?: pulumi.Input<string>;
    /**
     * The registration token.
     */
    registrationToken: pulumi.Input<string>;
}
