// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CodeEngineAllowedOutboundDestination extends pulumi.CustomResource {
    /**
     * Get an existing CodeEngineAllowedOutboundDestination resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CodeEngineAllowedOutboundDestinationState, opts?: pulumi.CustomResourceOptions): CodeEngineAllowedOutboundDestination {
        return new CodeEngineAllowedOutboundDestination(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ibmcloud:index/codeEngineAllowedOutboundDestination:CodeEngineAllowedOutboundDestination';

    /**
     * Returns true if the given object is an instance of CodeEngineAllowedOutboundDestination.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CodeEngineAllowedOutboundDestination {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CodeEngineAllowedOutboundDestination.__pulumiType;
    }

    /**
     * The IPv4 address range.
     */
    declare public readonly cidrBlock: pulumi.Output<string | undefined>;
    /**
     * The version of the allowed outbound destination, which is used to achieve optimistic locking.
     */
    declare public /*out*/ readonly entityTag: pulumi.Output<string>;
    declare public /*out*/ readonly etag: pulumi.Output<string>;
    /**
     * The name of the CIDR block.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ID of the project.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * Specify the type of the allowed outbound destination. Allowed types are: 'cidr_block'.
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a CodeEngineAllowedOutboundDestination resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CodeEngineAllowedOutboundDestinationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CodeEngineAllowedOutboundDestinationArgs | CodeEngineAllowedOutboundDestinationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CodeEngineAllowedOutboundDestinationState | undefined;
            resourceInputs["cidrBlock"] = state?.cidrBlock;
            resourceInputs["entityTag"] = state?.entityTag;
            resourceInputs["etag"] = state?.etag;
            resourceInputs["name"] = state?.name;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as CodeEngineAllowedOutboundDestinationArgs | undefined;
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["cidrBlock"] = args?.cidrBlock;
            resourceInputs["name"] = args?.name;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["type"] = args?.type;
            resourceInputs["entityTag"] = undefined /*out*/;
            resourceInputs["etag"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CodeEngineAllowedOutboundDestination.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CodeEngineAllowedOutboundDestination resources.
 */
export interface CodeEngineAllowedOutboundDestinationState {
    /**
     * The IPv4 address range.
     */
    cidrBlock?: pulumi.Input<string>;
    /**
     * The version of the allowed outbound destination, which is used to achieve optimistic locking.
     */
    entityTag?: pulumi.Input<string>;
    etag?: pulumi.Input<string>;
    /**
     * The name of the CIDR block.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the project.
     */
    projectId?: pulumi.Input<string>;
    /**
     * Specify the type of the allowed outbound destination. Allowed types are: 'cidr_block'.
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CodeEngineAllowedOutboundDestination resource.
 */
export interface CodeEngineAllowedOutboundDestinationArgs {
    /**
     * The IPv4 address range.
     */
    cidrBlock?: pulumi.Input<string>;
    /**
     * The name of the CIDR block.
     */
    name?: pulumi.Input<string>;
    /**
     * The ID of the project.
     */
    projectId: pulumi.Input<string>;
    /**
     * Specify the type of the allowed outbound destination. Allowed types are: 'cidr_block'.
     */
    type: pulumi.Input<string>;
}
