// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class EnDestinationIos extends pulumi.CustomResource {
    /**
     * Get an existing EnDestinationIos resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EnDestinationIosState, opts?: pulumi.CustomResourceOptions): EnDestinationIos {
        return new EnDestinationIos(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ibmcloud:index/enDestinationIos:EnDestinationIos';

    /**
     * Returns true if the given object is an instance of EnDestinationIos.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EnDestinationIos {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EnDestinationIos.__pulumiType;
    }

    /**
     * The Certificate File.
     */
    declare public readonly certificate: pulumi.Output<string>;
    /**
     * The Certificate Content Type to be set p8/p12.
     */
    declare public readonly certificateContentType: pulumi.Output<string>;
    /**
     * Whether to collect the failed event in Cloud Object Storage bucket
     */
    declare public readonly collectFailedEvents: pulumi.Output<boolean | undefined>;
    /**
     * Payload describing a destination configuration.
     */
    declare public readonly config: pulumi.Output<outputs.EnDestinationIosConfig | undefined>;
    /**
     * The Destination description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Destination ID
     */
    declare public /*out*/ readonly destinationId: pulumi.Output<string>;
    /**
     * Unique identifier for IBM Cloud Event Notifications instance.
     */
    declare public readonly instanceGuid: pulumi.Output<string>;
    /**
     * The Destintion name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Number of subscriptions.
     */
    declare public /*out*/ readonly subscriptionCount: pulumi.Output<number>;
    /**
     * List of subscriptions.
     */
    declare public /*out*/ readonly subscriptionNames: pulumi.Output<string[]>;
    /**
     * The type of Destination type push_ios.
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * Last updated time.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a EnDestinationIos resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EnDestinationIosArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EnDestinationIosArgs | EnDestinationIosState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EnDestinationIosState | undefined;
            resourceInputs["certificate"] = state?.certificate;
            resourceInputs["certificateContentType"] = state?.certificateContentType;
            resourceInputs["collectFailedEvents"] = state?.collectFailedEvents;
            resourceInputs["config"] = state?.config;
            resourceInputs["description"] = state?.description;
            resourceInputs["destinationId"] = state?.destinationId;
            resourceInputs["instanceGuid"] = state?.instanceGuid;
            resourceInputs["name"] = state?.name;
            resourceInputs["subscriptionCount"] = state?.subscriptionCount;
            resourceInputs["subscriptionNames"] = state?.subscriptionNames;
            resourceInputs["type"] = state?.type;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as EnDestinationIosArgs | undefined;
            if (args?.certificate === undefined && !opts.urn) {
                throw new Error("Missing required property 'certificate'");
            }
            if (args?.certificateContentType === undefined && !opts.urn) {
                throw new Error("Missing required property 'certificateContentType'");
            }
            if (args?.instanceGuid === undefined && !opts.urn) {
                throw new Error("Missing required property 'instanceGuid'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["certificate"] = args?.certificate;
            resourceInputs["certificateContentType"] = args?.certificateContentType;
            resourceInputs["collectFailedEvents"] = args?.collectFailedEvents;
            resourceInputs["config"] = args?.config;
            resourceInputs["description"] = args?.description;
            resourceInputs["instanceGuid"] = args?.instanceGuid;
            resourceInputs["name"] = args?.name;
            resourceInputs["type"] = args?.type;
            resourceInputs["destinationId"] = undefined /*out*/;
            resourceInputs["subscriptionCount"] = undefined /*out*/;
            resourceInputs["subscriptionNames"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EnDestinationIos.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EnDestinationIos resources.
 */
export interface EnDestinationIosState {
    /**
     * The Certificate File.
     */
    certificate?: pulumi.Input<string>;
    /**
     * The Certificate Content Type to be set p8/p12.
     */
    certificateContentType?: pulumi.Input<string>;
    /**
     * Whether to collect the failed event in Cloud Object Storage bucket
     */
    collectFailedEvents?: pulumi.Input<boolean>;
    /**
     * Payload describing a destination configuration.
     */
    config?: pulumi.Input<inputs.EnDestinationIosConfig>;
    /**
     * The Destination description.
     */
    description?: pulumi.Input<string>;
    /**
     * Destination ID
     */
    destinationId?: pulumi.Input<string>;
    /**
     * Unique identifier for IBM Cloud Event Notifications instance.
     */
    instanceGuid?: pulumi.Input<string>;
    /**
     * The Destintion name.
     */
    name?: pulumi.Input<string>;
    /**
     * Number of subscriptions.
     */
    subscriptionCount?: pulumi.Input<number>;
    /**
     * List of subscriptions.
     */
    subscriptionNames?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The type of Destination type push_ios.
     */
    type?: pulumi.Input<string>;
    /**
     * Last updated time.
     */
    updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a EnDestinationIos resource.
 */
export interface EnDestinationIosArgs {
    /**
     * The Certificate File.
     */
    certificate: pulumi.Input<string>;
    /**
     * The Certificate Content Type to be set p8/p12.
     */
    certificateContentType: pulumi.Input<string>;
    /**
     * Whether to collect the failed event in Cloud Object Storage bucket
     */
    collectFailedEvents?: pulumi.Input<boolean>;
    /**
     * Payload describing a destination configuration.
     */
    config?: pulumi.Input<inputs.EnDestinationIosConfig>;
    /**
     * The Destination description.
     */
    description?: pulumi.Input<string>;
    /**
     * Unique identifier for IBM Cloud Event Notifications instance.
     */
    instanceGuid: pulumi.Input<string>;
    /**
     * The Destintion name.
     */
    name?: pulumi.Input<string>;
    /**
     * The type of Destination type push_ios.
     */
    type: pulumi.Input<string>;
}
