// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getBackupRecoveryProtectionGroupRuns(args: GetBackupRecoveryProtectionGroupRunsArgs, opts?: pulumi.InvokeOptions): Promise<GetBackupRecoveryProtectionGroupRunsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getBackupRecoveryProtectionGroupRuns:getBackupRecoveryProtectionGroupRuns", {
        "archivalRunStatuses": args.archivalRunStatuses,
        "cloudSpinRunStatuses": args.cloudSpinRunStatuses,
        "endTimeUsecs": args.endTimeUsecs,
        "endpointType": args.endpointType,
        "excludeNonRestorableRuns": args.excludeNonRestorableRuns,
        "filterByCopyTaskEndTime": args.filterByCopyTaskEndTime,
        "filterByEndTime": args.filterByEndTime,
        "includeObjectDetails": args.includeObjectDetails,
        "instanceId": args.instanceId,
        "localBackupRunStatuses": args.localBackupRunStatuses,
        "numRuns": args.numRuns,
        "onlyReturnSuccessfulCopyRun": args.onlyReturnSuccessfulCopyRun,
        "protectionGroupId": args.protectionGroupId,
        "region": args.region,
        "replicationRunStatuses": args.replicationRunStatuses,
        "requestInitiatorType": args.requestInitiatorType,
        "runId": args.runId,
        "runTags": args.runTags,
        "runTypes": args.runTypes,
        "snapshotTargetTypes": args.snapshotTargetTypes,
        "startTimeUsecs": args.startTimeUsecs,
        "useCachedData": args.useCachedData,
        "xIbmTenantId": args.xIbmTenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getBackupRecoveryProtectionGroupRuns.
 */
export interface GetBackupRecoveryProtectionGroupRunsArgs {
    archivalRunStatuses?: string[];
    cloudSpinRunStatuses?: string[];
    endTimeUsecs?: number;
    endpointType?: string;
    excludeNonRestorableRuns?: boolean;
    filterByCopyTaskEndTime?: boolean;
    filterByEndTime?: boolean;
    includeObjectDetails?: boolean;
    instanceId?: string;
    localBackupRunStatuses?: string[];
    numRuns?: number;
    onlyReturnSuccessfulCopyRun?: boolean;
    protectionGroupId: string;
    region?: string;
    replicationRunStatuses?: string[];
    requestInitiatorType?: string;
    runId?: string;
    runTags?: string[];
    runTypes?: string[];
    snapshotTargetTypes?: string[];
    startTimeUsecs?: number;
    useCachedData?: boolean;
    xIbmTenantId: string;
}

/**
 * A collection of values returned by getBackupRecoveryProtectionGroupRuns.
 */
export interface GetBackupRecoveryProtectionGroupRunsResult {
    readonly archivalRunStatuses?: string[];
    readonly cloudSpinRunStatuses?: string[];
    readonly endTimeUsecs?: number;
    readonly endpointType?: string;
    readonly excludeNonRestorableRuns?: boolean;
    readonly filterByCopyTaskEndTime?: boolean;
    readonly filterByEndTime?: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly includeObjectDetails?: boolean;
    readonly instanceId?: string;
    readonly localBackupRunStatuses?: string[];
    readonly numRuns?: number;
    readonly onlyReturnSuccessfulCopyRun?: boolean;
    readonly protectionGroupId: string;
    readonly region: string;
    readonly replicationRunStatuses?: string[];
    readonly requestInitiatorType?: string;
    readonly runId?: string;
    readonly runTags?: string[];
    readonly runTypes?: string[];
    readonly runs: outputs.GetBackupRecoveryProtectionGroupRunsRun[];
    readonly snapshotTargetTypes?: string[];
    readonly startTimeUsecs?: number;
    readonly totalRuns: number;
    readonly useCachedData?: boolean;
    readonly xIbmTenantId: string;
}
export function getBackupRecoveryProtectionGroupRunsOutput(args: GetBackupRecoveryProtectionGroupRunsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetBackupRecoveryProtectionGroupRunsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getBackupRecoveryProtectionGroupRuns:getBackupRecoveryProtectionGroupRuns", {
        "archivalRunStatuses": args.archivalRunStatuses,
        "cloudSpinRunStatuses": args.cloudSpinRunStatuses,
        "endTimeUsecs": args.endTimeUsecs,
        "endpointType": args.endpointType,
        "excludeNonRestorableRuns": args.excludeNonRestorableRuns,
        "filterByCopyTaskEndTime": args.filterByCopyTaskEndTime,
        "filterByEndTime": args.filterByEndTime,
        "includeObjectDetails": args.includeObjectDetails,
        "instanceId": args.instanceId,
        "localBackupRunStatuses": args.localBackupRunStatuses,
        "numRuns": args.numRuns,
        "onlyReturnSuccessfulCopyRun": args.onlyReturnSuccessfulCopyRun,
        "protectionGroupId": args.protectionGroupId,
        "region": args.region,
        "replicationRunStatuses": args.replicationRunStatuses,
        "requestInitiatorType": args.requestInitiatorType,
        "runId": args.runId,
        "runTags": args.runTags,
        "runTypes": args.runTypes,
        "snapshotTargetTypes": args.snapshotTargetTypes,
        "startTimeUsecs": args.startTimeUsecs,
        "useCachedData": args.useCachedData,
        "xIbmTenantId": args.xIbmTenantId,
    }, opts);
}

/**
 * A collection of arguments for invoking getBackupRecoveryProtectionGroupRuns.
 */
export interface GetBackupRecoveryProtectionGroupRunsOutputArgs {
    archivalRunStatuses?: pulumi.Input<pulumi.Input<string>[]>;
    cloudSpinRunStatuses?: pulumi.Input<pulumi.Input<string>[]>;
    endTimeUsecs?: pulumi.Input<number>;
    endpointType?: pulumi.Input<string>;
    excludeNonRestorableRuns?: pulumi.Input<boolean>;
    filterByCopyTaskEndTime?: pulumi.Input<boolean>;
    filterByEndTime?: pulumi.Input<boolean>;
    includeObjectDetails?: pulumi.Input<boolean>;
    instanceId?: pulumi.Input<string>;
    localBackupRunStatuses?: pulumi.Input<pulumi.Input<string>[]>;
    numRuns?: pulumi.Input<number>;
    onlyReturnSuccessfulCopyRun?: pulumi.Input<boolean>;
    protectionGroupId: pulumi.Input<string>;
    region?: pulumi.Input<string>;
    replicationRunStatuses?: pulumi.Input<pulumi.Input<string>[]>;
    requestInitiatorType?: pulumi.Input<string>;
    runId?: pulumi.Input<string>;
    runTags?: pulumi.Input<pulumi.Input<string>[]>;
    runTypes?: pulumi.Input<pulumi.Input<string>[]>;
    snapshotTargetTypes?: pulumi.Input<pulumi.Input<string>[]>;
    startTimeUsecs?: pulumi.Input<number>;
    useCachedData?: pulumi.Input<boolean>;
    xIbmTenantId: pulumi.Input<string>;
}
