// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCosBackupPolicy(args: GetCosBackupPolicyArgs, opts?: pulumi.InvokeOptions): Promise<GetCosBackupPolicyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getCosBackupPolicy:getCosBackupPolicy", {
        "bucketName": args.bucketName,
        "policyId": args.policyId,
    }, opts);
}

/**
 * A collection of arguments for invoking getCosBackupPolicy.
 */
export interface GetCosBackupPolicyArgs {
    bucketName: string;
    policyId: string;
}

/**
 * A collection of values returned by getCosBackupPolicy.
 */
export interface GetCosBackupPolicyResult {
    readonly backupType: string;
    readonly bucketName: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly initialDeleteAfterDays: number;
    readonly policyId: string;
    readonly policyName: string;
    readonly targetBackupVaultCrn: string;
}
export function getCosBackupPolicyOutput(args: GetCosBackupPolicyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCosBackupPolicyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getCosBackupPolicy:getCosBackupPolicy", {
        "bucketName": args.bucketName,
        "policyId": args.policyId,
    }, opts);
}

/**
 * A collection of arguments for invoking getCosBackupPolicy.
 */
export interface GetCosBackupPolicyOutputArgs {
    bucketName: pulumi.Input<string>;
    policyId: pulumi.Input<string>;
}
