// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getCisRulesetVersions(args: GetCisRulesetVersionsArgs, opts?: pulumi.InvokeOptions): Promise<GetCisRulesetVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getCisRulesetVersions:getCisRulesetVersions", {
        "cisId": args.cisId,
        "domainId": args.domainId,
        "rulesetId": args.rulesetId,
        "version": args.version,
    }, opts);
}

/**
 * A collection of arguments for invoking getCisRulesetVersions.
 */
export interface GetCisRulesetVersionsArgs {
    cisId: string;
    domainId?: string;
    rulesetId: string;
    version?: string;
}

/**
 * A collection of values returned by getCisRulesetVersions.
 */
export interface GetCisRulesetVersionsResult {
    readonly cisId: string;
    readonly domainId?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly rulesetId: string;
    readonly rulesetVersions: outputs.GetCisRulesetVersionsRulesetVersion[];
    readonly rulesets: outputs.GetCisRulesetVersionsRuleset[];
    readonly version?: string;
}
export function getCisRulesetVersionsOutput(args: GetCisRulesetVersionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCisRulesetVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getCisRulesetVersions:getCisRulesetVersions", {
        "cisId": args.cisId,
        "domainId": args.domainId,
        "rulesetId": args.rulesetId,
        "version": args.version,
    }, opts);
}

/**
 * A collection of arguments for invoking getCisRulesetVersions.
 */
export interface GetCisRulesetVersionsOutputArgs {
    cisId: pulumi.Input<string>;
    domainId?: pulumi.Input<string>;
    rulesetId: pulumi.Input<string>;
    version?: pulumi.Input<string>;
}
