// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getCdToolchains(args: GetCdToolchainsArgs, opts?: pulumi.InvokeOptions): Promise<GetCdToolchainsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getCdToolchains:getCdToolchains", {
        "name": args.name,
        "resourceGroupId": args.resourceGroupId,
    }, opts);
}

/**
 * A collection of arguments for invoking getCdToolchains.
 */
export interface GetCdToolchainsArgs {
    name?: string;
    resourceGroupId: string;
}

/**
 * A collection of values returned by getCdToolchains.
 */
export interface GetCdToolchainsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name?: string;
    readonly resourceGroupId: string;
    readonly toolchains: outputs.GetCdToolchainsToolchain[];
}
export function getCdToolchainsOutput(args: GetCdToolchainsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetCdToolchainsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getCdToolchains:getCdToolchains", {
        "name": args.name,
        "resourceGroupId": args.resourceGroupId,
    }, opts);
}

/**
 * A collection of arguments for invoking getCdToolchains.
 */
export interface GetCdToolchainsOutputArgs {
    name?: pulumi.Input<string>;
    resourceGroupId: pulumi.Input<string>;
}
