// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDb2WhitelistIp(args: GetDb2WhitelistIpArgs, opts?: pulumi.InvokeOptions): Promise<GetDb2WhitelistIpResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getDb2WhitelistIp:getDb2WhitelistIp", {
        "xDeploymentId": args.xDeploymentId,
    }, opts);
}

/**
 * A collection of arguments for invoking getDb2WhitelistIp.
 */
export interface GetDb2WhitelistIpArgs {
    xDeploymentId: string;
}

/**
 * A collection of values returned by getDb2WhitelistIp.
 */
export interface GetDb2WhitelistIpResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ipAddresses: outputs.GetDb2WhitelistIpIpAddress[];
    readonly xDeploymentId: string;
}
export function getDb2WhitelistIpOutput(args: GetDb2WhitelistIpOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDb2WhitelistIpResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getDb2WhitelistIp:getDb2WhitelistIp", {
        "xDeploymentId": args.xDeploymentId,
    }, opts);
}

/**
 * A collection of arguments for invoking getDb2WhitelistIp.
 */
export interface GetDb2WhitelistIpOutputArgs {
    xDeploymentId: pulumi.Input<string>;
}
