// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getEnAppConfigurationTemplate(args: GetEnAppConfigurationTemplateArgs, opts?: pulumi.InvokeOptions): Promise<GetEnAppConfigurationTemplateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getEnAppConfigurationTemplate:getEnAppConfigurationTemplate", {
        "instanceGuid": args.instanceGuid,
        "templateId": args.templateId,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnAppConfigurationTemplate.
 */
export interface GetEnAppConfigurationTemplateArgs {
    instanceGuid: string;
    templateId: string;
}

/**
 * A collection of values returned by getEnAppConfigurationTemplate.
 */
export interface GetEnAppConfigurationTemplateResult {
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceGuid: string;
    readonly name: string;
    readonly subscriptionCount: number;
    readonly subscriptionNames: string[];
    readonly templateId: string;
    readonly type: string;
    readonly updatedAt: string;
}
export function getEnAppConfigurationTemplateOutput(args: GetEnAppConfigurationTemplateOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEnAppConfigurationTemplateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getEnAppConfigurationTemplate:getEnAppConfigurationTemplate", {
        "instanceGuid": args.instanceGuid,
        "templateId": args.templateId,
    }, opts);
}

/**
 * A collection of arguments for invoking getEnAppConfigurationTemplate.
 */
export interface GetEnAppConfigurationTemplateOutputArgs {
    instanceGuid: pulumi.Input<string>;
    templateId: pulumi.Input<string>;
}
