// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getIamRoleTemplate(opts?: pulumi.InvokeOptions): Promise<GetIamRoleTemplateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getIamRoleTemplate:getIamRoleTemplate", {
    }, opts);
}

/**
 * A collection of values returned by getIamRoleTemplate.
 */
export interface GetIamRoleTemplateResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly roleTemplates: outputs.GetIamRoleTemplateRoleTemplate[];
}
export function getIamRoleTemplateOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIamRoleTemplateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getIamRoleTemplate:getIamRoleTemplate", {
    }, opts);
}
