// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getIsBareMetalServerProfiles(opts?: pulumi.InvokeOptions): Promise<GetIsBareMetalServerProfilesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getIsBareMetalServerProfiles:getIsBareMetalServerProfiles", {
    }, opts);
}

/**
 * A collection of values returned by getIsBareMetalServerProfiles.
 */
export interface GetIsBareMetalServerProfilesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly profiles: outputs.GetIsBareMetalServerProfilesProfile[];
}
export function getIsBareMetalServerProfilesOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIsBareMetalServerProfilesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getIsBareMetalServerProfiles:getIsBareMetalServerProfiles", {
    }, opts);
}
