// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getIsRegion(args?: GetIsRegionArgs, opts?: pulumi.InvokeOptions): Promise<GetIsRegionResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getIsRegion:getIsRegion", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getIsRegion.
 */
export interface GetIsRegionArgs {
    name?: string;
}

/**
 * A collection of values returned by getIsRegion.
 */
export interface GetIsRegionResult {
    readonly endpoint: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name?: string;
    readonly status: string;
}
export function getIsRegionOutput(args?: GetIsRegionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIsRegionResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getIsRegion:getIsRegion", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getIsRegion.
 */
export interface GetIsRegionOutputArgs {
    name?: pulumi.Input<string>;
}
