// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getLogsViewFolders(args: GetLogsViewFoldersArgs, opts?: pulumi.InvokeOptions): Promise<GetLogsViewFoldersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getLogsViewFolders:getLogsViewFolders", {
        "endpointType": args.endpointType,
        "instanceId": args.instanceId,
        "region": args.region,
    }, opts);
}

/**
 * A collection of arguments for invoking getLogsViewFolders.
 */
export interface GetLogsViewFoldersArgs {
    endpointType?: string;
    instanceId: string;
    region?: string;
}

/**
 * A collection of values returned by getLogsViewFolders.
 */
export interface GetLogsViewFoldersResult {
    readonly endpointType?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceId: string;
    readonly region: string;
    readonly viewFolders: outputs.GetLogsViewFoldersViewFolder[];
}
export function getLogsViewFoldersOutput(args: GetLogsViewFoldersOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetLogsViewFoldersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getLogsViewFolders:getLogsViewFolders", {
        "endpointType": args.endpointType,
        "instanceId": args.instanceId,
        "region": args.region,
    }, opts);
}

/**
 * A collection of arguments for invoking getLogsViewFolders.
 */
export interface GetLogsViewFoldersOutputArgs {
    endpointType?: pulumi.Input<string>;
    instanceId: pulumi.Input<string>;
    region?: pulumi.Input<string>;
}
