// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPiInstanceNetwork(args: GetPiInstanceNetworkArgs, opts?: pulumi.InvokeOptions): Promise<GetPiInstanceNetworkResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getPiInstanceNetwork:getPiInstanceNetwork", {
        "piCloudInstanceId": args.piCloudInstanceId,
        "piInstanceId": args.piInstanceId,
        "piNetworkId": args.piNetworkId,
    }, opts);
}

/**
 * A collection of arguments for invoking getPiInstanceNetwork.
 */
export interface GetPiInstanceNetworkArgs {
    piCloudInstanceId: string;
    piInstanceId: string;
    piNetworkId: string;
}

/**
 * A collection of values returned by getPiInstanceNetwork.
 */
export interface GetPiInstanceNetworkResult {
    readonly externalIp: string;
    readonly href: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ipAddress: string;
    readonly macAddress: string;
    readonly networkId: string;
    readonly networkInterfaceId: string;
    readonly networkName: string;
    readonly networkSecurityGroupIds: string[];
    readonly networkSecurityGroupsHreves: string[];
    readonly piCloudInstanceId: string;
    readonly piInstanceId: string;
    readonly piNetworkId: string;
    readonly type: string;
    readonly version: number;
}
export function getPiInstanceNetworkOutput(args: GetPiInstanceNetworkOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPiInstanceNetworkResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getPiInstanceNetwork:getPiInstanceNetwork", {
        "piCloudInstanceId": args.piCloudInstanceId,
        "piInstanceId": args.piInstanceId,
        "piNetworkId": args.piNetworkId,
    }, opts);
}

/**
 * A collection of arguments for invoking getPiInstanceNetwork.
 */
export interface GetPiInstanceNetworkOutputArgs {
    piCloudInstanceId: pulumi.Input<string>;
    piInstanceId: pulumi.Input<string>;
    piNetworkId: pulumi.Input<string>;
}
