// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getPiRoutes(args: GetPiRoutesArgs, opts?: pulumi.InvokeOptions): Promise<GetPiRoutesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getPiRoutes:getPiRoutes", {
        "piCloudInstanceId": args.piCloudInstanceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getPiRoutes.
 */
export interface GetPiRoutesArgs {
    piCloudInstanceId: string;
}

/**
 * A collection of values returned by getPiRoutes.
 */
export interface GetPiRoutesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly piCloudInstanceId: string;
    readonly routes: outputs.GetPiRoutesRoute[];
}
export function getPiRoutesOutput(args: GetPiRoutesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPiRoutesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getPiRoutes:getPiRoutes", {
        "piCloudInstanceId": args.piCloudInstanceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getPiRoutes.
 */
export interface GetPiRoutesOutputArgs {
    piCloudInstanceId: pulumi.Input<string>;
}
