// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getResourceGroups(args?: GetResourceGroupsArgs, opts?: pulumi.InvokeOptions): Promise<GetResourceGroupsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getResourceGroups:getResourceGroups", {
        "date": args.date,
        "includeDeleted": args.includeDeleted,
        "isDefault": args.isDefault,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getResourceGroups.
 */
export interface GetResourceGroupsArgs {
    date?: string;
    includeDeleted?: boolean;
    isDefault?: boolean;
    name?: string;
}

/**
 * A collection of values returned by getResourceGroups.
 */
export interface GetResourceGroupsResult {
    readonly date?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly includeDeleted?: boolean;
    readonly isDefault?: boolean;
    readonly name?: string;
    readonly resourceGroups: outputs.GetResourceGroupsResourceGroup[];
}
export function getResourceGroupsOutput(args?: GetResourceGroupsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetResourceGroupsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getResourceGroups:getResourceGroups", {
        "date": args.date,
        "includeDeleted": args.includeDeleted,
        "isDefault": args.isDefault,
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getResourceGroups.
 */
export interface GetResourceGroupsOutputArgs {
    date?: pulumi.Input<string | undefined>;
    includeDeleted?: pulumi.Input<boolean | undefined>;
    isDefault?: pulumi.Input<boolean | undefined>;
    name?: pulumi.Input<string | undefined>;
}
