// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSccReportControls(args: GetSccReportControlsArgs, opts?: pulumi.InvokeOptions): Promise<GetSccReportControlsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ibmcloud:index/getSccReportControls:getSccReportControls", {
        "controlCategory": args.controlCategory,
        "controlDescription": args.controlDescription,
        "controlId": args.controlId,
        "controlName": args.controlName,
        "instanceId": args.instanceId,
        "reportId": args.reportId,
        "sort": args.sort,
        "status": args.status,
    }, opts);
}

/**
 * A collection of arguments for invoking getSccReportControls.
 */
export interface GetSccReportControlsArgs {
    controlCategory?: string;
    controlDescription?: string;
    controlId?: string;
    controlName?: string;
    instanceId: string;
    reportId: string;
    sort?: string;
    status?: string;
}

/**
 * A collection of values returned by getSccReportControls.
 */
export interface GetSccReportControlsResult {
    readonly compliantCount: number;
    readonly controlCategory?: string;
    readonly controlDescription?: string;
    readonly controlId?: string;
    readonly controlName?: string;
    readonly controls: outputs.GetSccReportControlsControl[];
    readonly homeAccountId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceId: string;
    readonly notCompliantCount: number;
    readonly reportId: string;
    readonly sort?: string;
    readonly status?: string;
    readonly totalCount: number;
    readonly unableToPerformCount: number;
    readonly userEvaluationRequiredCount: number;
}
export function getSccReportControlsOutput(args: GetSccReportControlsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSccReportControlsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ibmcloud:index/getSccReportControls:getSccReportControls", {
        "controlCategory": args.controlCategory,
        "controlDescription": args.controlDescription,
        "controlId": args.controlId,
        "controlName": args.controlName,
        "instanceId": args.instanceId,
        "reportId": args.reportId,
        "sort": args.sort,
        "status": args.status,
    }, opts);
}

/**
 * A collection of arguments for invoking getSccReportControls.
 */
export interface GetSccReportControlsOutputArgs {
    controlCategory?: pulumi.Input<string>;
    controlDescription?: pulumi.Input<string>;
    controlId?: pulumi.Input<string>;
    controlName?: pulumi.Input<string>;
    instanceId: pulumi.Input<string>;
    reportId: pulumi.Input<string>;
    sort?: pulumi.Input<string>;
    status?: pulumi.Input<string>;
}
