// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class IsInstanceTemplate extends pulumi.CustomResource {
    /**
     * Get an existing IsInstanceTemplate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IsInstanceTemplateState, opts?: pulumi.CustomResourceOptions): IsInstanceTemplate {
        return new IsInstanceTemplate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ibmcloud:index/isInstanceTemplate:IsInstanceTemplate';

    /**
     * Returns true if the given object is an instance of IsInstanceTemplate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IsInstanceTemplate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IsInstanceTemplate.__pulumiType;
    }

    /**
     * The availability policy to use for this virtual server instance
     */
    declare public readonly availabilityPolicyHostFailure: pulumi.Output<string>;
    declare public readonly bootVolume: pulumi.Output<outputs.IsInstanceTemplateBootVolume>;
    /**
     * The catalog offering or offering version to use when provisioning this virtual server instance template. If an offering is specified, the latest version of that offering will be used. The specified offering or offering version may be in a different account in the same enterprise, subject to IAM policies.
     */
    declare public readonly catalogOffering: pulumi.Output<outputs.IsInstanceTemplateCatalogOffering | undefined>;
    /**
     * The cluster network attachments to create for this virtual server instance. A cluster network attachment represents a device that is connected to a cluster network. The number of network attachments must match one of the values from the instance profile's `clusterNetworkAttachmentCount` before the instance can be started.
     */
    declare public readonly clusterNetworkAttachments: pulumi.Output<outputs.IsInstanceTemplateClusterNetworkAttachment[] | undefined>;
    /**
     * The confidential compute mode to use for this virtual server instance.If unspecified, the default confidential compute mode from the profile will be used.
     */
    declare public readonly confidentialComputeMode: pulumi.Output<string | undefined>;
    /**
     * The CRN for the instance
     */
    declare public /*out*/ readonly crn: pulumi.Output<string>;
    /**
     * Unique Identifier of the Dedicated Host where the instance will be placed
     */
    declare public readonly dedicatedHost: pulumi.Output<string | undefined>;
    /**
     * Unique Identifier of the Dedicated Host Group where the instance will be placed
     */
    declare public readonly dedicatedHostGroup: pulumi.Output<string | undefined>;
    /**
     * If set to `true`, the system will create a link to the specified `target` trusted profile during instance creation. Regardless of whether a link is created by the system or manually using the IAM Identity service, it will be automatically deleted when the instance is deleted.
     */
    declare public readonly defaultTrustedProfileAutoLink: pulumi.Output<boolean>;
    /**
     * The unique identifier or CRN of the default IAM trusted profile to use for this virtual server instance.
     */
    declare public readonly defaultTrustedProfileTarget: pulumi.Output<string | undefined>;
    /**
     * Indicates whether secure boot is enabled for this virtual server instance.If unspecified, the default secure boot mode from the profile will be used.
     */
    declare public readonly enableSecureBoot: pulumi.Output<boolean | undefined>;
    /**
     * image name
     */
    declare public readonly image: pulumi.Output<string | undefined>;
    /**
     * SSH key Ids for the instance template
     */
    declare public readonly keys: pulumi.Output<string[]>;
    /**
     * The metadata service configuration
     */
    declare public readonly metadataService: pulumi.Output<outputs.IsInstanceTemplateMetadataService>;
    /**
     * Indicates whether the metadata service endpoint is available to the virtual server instance
     *
     * @deprecated Use metadataService instead
     */
    declare public readonly metadataServiceEnabled: pulumi.Output<boolean>;
    /**
     * Instance Template name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The network attachments for this virtual server instance, including the primary network attachment.
     */
    declare public readonly networkAttachments: pulumi.Output<outputs.IsInstanceTemplateNetworkAttachment[] | undefined>;
    declare public readonly networkInterfaces: pulumi.Output<outputs.IsInstanceTemplateNetworkInterface[] | undefined>;
    /**
     * Unique Identifier of the Placement Group for restricting the placement of the instance
     */
    declare public readonly placementGroup: pulumi.Output<string | undefined>;
    /**
     * The placement restrictions for the virtual server instance.
     */
    declare public /*out*/ readonly placementTargets: pulumi.Output<outputs.IsInstanceTemplatePlacementTarget[]>;
    /**
     * The primary network attachment for this virtual server instance.
     */
    declare public readonly primaryNetworkAttachment: pulumi.Output<outputs.IsInstanceTemplatePrimaryNetworkAttachment | undefined>;
    /**
     * Primary Network interface info
     */
    declare public readonly primaryNetworkInterface: pulumi.Output<outputs.IsInstanceTemplatePrimaryNetworkInterface | undefined>;
    /**
     * Profile info
     */
    declare public readonly profile: pulumi.Output<string>;
    declare public readonly reservationAffinities: pulumi.Output<outputs.IsInstanceTemplateReservationAffinity[]>;
    /**
     * Instance template resource group
     */
    declare public readonly resourceGroup: pulumi.Output<string>;
    /**
     * The amount of bandwidth (in megabits per second) allocated exclusively to instance storage volumes
     */
    declare public readonly totalVolumeBandwidth: pulumi.Output<number | undefined>;
    /**
     * User data given for the instance
     */
    declare public readonly userData: pulumi.Output<string | undefined>;
    declare public readonly volumeAttachments: pulumi.Output<outputs.IsInstanceTemplateVolumeAttachment[] | undefined>;
    /**
     * The volume bandwidth QoS mode for this virtual server instance.
     */
    declare public readonly volumeBandwidthQosMode: pulumi.Output<string | undefined>;
    /**
     * VPC id
     */
    declare public readonly vpc: pulumi.Output<string>;
    /**
     * Zone name
     */
    declare public readonly zone: pulumi.Output<string>;

    /**
     * Create a IsInstanceTemplate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IsInstanceTemplateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IsInstanceTemplateArgs | IsInstanceTemplateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IsInstanceTemplateState | undefined;
            resourceInputs["availabilityPolicyHostFailure"] = state?.availabilityPolicyHostFailure;
            resourceInputs["bootVolume"] = state?.bootVolume;
            resourceInputs["catalogOffering"] = state?.catalogOffering;
            resourceInputs["clusterNetworkAttachments"] = state?.clusterNetworkAttachments;
            resourceInputs["confidentialComputeMode"] = state?.confidentialComputeMode;
            resourceInputs["crn"] = state?.crn;
            resourceInputs["dedicatedHost"] = state?.dedicatedHost;
            resourceInputs["dedicatedHostGroup"] = state?.dedicatedHostGroup;
            resourceInputs["defaultTrustedProfileAutoLink"] = state?.defaultTrustedProfileAutoLink;
            resourceInputs["defaultTrustedProfileTarget"] = state?.defaultTrustedProfileTarget;
            resourceInputs["enableSecureBoot"] = state?.enableSecureBoot;
            resourceInputs["image"] = state?.image;
            resourceInputs["keys"] = state?.keys;
            resourceInputs["metadataService"] = state?.metadataService;
            resourceInputs["metadataServiceEnabled"] = state?.metadataServiceEnabled;
            resourceInputs["name"] = state?.name;
            resourceInputs["networkAttachments"] = state?.networkAttachments;
            resourceInputs["networkInterfaces"] = state?.networkInterfaces;
            resourceInputs["placementGroup"] = state?.placementGroup;
            resourceInputs["placementTargets"] = state?.placementTargets;
            resourceInputs["primaryNetworkAttachment"] = state?.primaryNetworkAttachment;
            resourceInputs["primaryNetworkInterface"] = state?.primaryNetworkInterface;
            resourceInputs["profile"] = state?.profile;
            resourceInputs["reservationAffinities"] = state?.reservationAffinities;
            resourceInputs["resourceGroup"] = state?.resourceGroup;
            resourceInputs["totalVolumeBandwidth"] = state?.totalVolumeBandwidth;
            resourceInputs["userData"] = state?.userData;
            resourceInputs["volumeAttachments"] = state?.volumeAttachments;
            resourceInputs["volumeBandwidthQosMode"] = state?.volumeBandwidthQosMode;
            resourceInputs["vpc"] = state?.vpc;
            resourceInputs["zone"] = state?.zone;
        } else {
            const args = argsOrState as IsInstanceTemplateArgs | undefined;
            if (args?.keys === undefined && !opts.urn) {
                throw new Error("Missing required property 'keys'");
            }
            if (args?.profile === undefined && !opts.urn) {
                throw new Error("Missing required property 'profile'");
            }
            if (args?.vpc === undefined && !opts.urn) {
                throw new Error("Missing required property 'vpc'");
            }
            if (args?.zone === undefined && !opts.urn) {
                throw new Error("Missing required property 'zone'");
            }
            resourceInputs["availabilityPolicyHostFailure"] = args?.availabilityPolicyHostFailure;
            resourceInputs["bootVolume"] = args?.bootVolume;
            resourceInputs["catalogOffering"] = args?.catalogOffering;
            resourceInputs["clusterNetworkAttachments"] = args?.clusterNetworkAttachments;
            resourceInputs["confidentialComputeMode"] = args?.confidentialComputeMode;
            resourceInputs["dedicatedHost"] = args?.dedicatedHost;
            resourceInputs["dedicatedHostGroup"] = args?.dedicatedHostGroup;
            resourceInputs["defaultTrustedProfileAutoLink"] = args?.defaultTrustedProfileAutoLink;
            resourceInputs["defaultTrustedProfileTarget"] = args?.defaultTrustedProfileTarget;
            resourceInputs["enableSecureBoot"] = args?.enableSecureBoot;
            resourceInputs["image"] = args?.image;
            resourceInputs["keys"] = args?.keys;
            resourceInputs["metadataService"] = args?.metadataService;
            resourceInputs["metadataServiceEnabled"] = args?.metadataServiceEnabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkAttachments"] = args?.networkAttachments;
            resourceInputs["networkInterfaces"] = args?.networkInterfaces;
            resourceInputs["placementGroup"] = args?.placementGroup;
            resourceInputs["primaryNetworkAttachment"] = args?.primaryNetworkAttachment;
            resourceInputs["primaryNetworkInterface"] = args?.primaryNetworkInterface;
            resourceInputs["profile"] = args?.profile;
            resourceInputs["reservationAffinities"] = args?.reservationAffinities;
            resourceInputs["resourceGroup"] = args?.resourceGroup;
            resourceInputs["totalVolumeBandwidth"] = args?.totalVolumeBandwidth;
            resourceInputs["userData"] = args?.userData;
            resourceInputs["volumeAttachments"] = args?.volumeAttachments;
            resourceInputs["volumeBandwidthQosMode"] = args?.volumeBandwidthQosMode;
            resourceInputs["vpc"] = args?.vpc;
            resourceInputs["zone"] = args?.zone;
            resourceInputs["crn"] = undefined /*out*/;
            resourceInputs["placementTargets"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IsInstanceTemplate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IsInstanceTemplate resources.
 */
export interface IsInstanceTemplateState {
    /**
     * The availability policy to use for this virtual server instance
     */
    availabilityPolicyHostFailure?: pulumi.Input<string>;
    bootVolume?: pulumi.Input<inputs.IsInstanceTemplateBootVolume>;
    /**
     * The catalog offering or offering version to use when provisioning this virtual server instance template. If an offering is specified, the latest version of that offering will be used. The specified offering or offering version may be in a different account in the same enterprise, subject to IAM policies.
     */
    catalogOffering?: pulumi.Input<inputs.IsInstanceTemplateCatalogOffering>;
    /**
     * The cluster network attachments to create for this virtual server instance. A cluster network attachment represents a device that is connected to a cluster network. The number of network attachments must match one of the values from the instance profile's `clusterNetworkAttachmentCount` before the instance can be started.
     */
    clusterNetworkAttachments?: pulumi.Input<pulumi.Input<inputs.IsInstanceTemplateClusterNetworkAttachment>[]>;
    /**
     * The confidential compute mode to use for this virtual server instance.If unspecified, the default confidential compute mode from the profile will be used.
     */
    confidentialComputeMode?: pulumi.Input<string>;
    /**
     * The CRN for the instance
     */
    crn?: pulumi.Input<string>;
    /**
     * Unique Identifier of the Dedicated Host where the instance will be placed
     */
    dedicatedHost?: pulumi.Input<string>;
    /**
     * Unique Identifier of the Dedicated Host Group where the instance will be placed
     */
    dedicatedHostGroup?: pulumi.Input<string>;
    /**
     * If set to `true`, the system will create a link to the specified `target` trusted profile during instance creation. Regardless of whether a link is created by the system or manually using the IAM Identity service, it will be automatically deleted when the instance is deleted.
     */
    defaultTrustedProfileAutoLink?: pulumi.Input<boolean>;
    /**
     * The unique identifier or CRN of the default IAM trusted profile to use for this virtual server instance.
     */
    defaultTrustedProfileTarget?: pulumi.Input<string>;
    /**
     * Indicates whether secure boot is enabled for this virtual server instance.If unspecified, the default secure boot mode from the profile will be used.
     */
    enableSecureBoot?: pulumi.Input<boolean>;
    /**
     * image name
     */
    image?: pulumi.Input<string>;
    /**
     * SSH key Ids for the instance template
     */
    keys?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The metadata service configuration
     */
    metadataService?: pulumi.Input<inputs.IsInstanceTemplateMetadataService>;
    /**
     * Indicates whether the metadata service endpoint is available to the virtual server instance
     *
     * @deprecated Use metadataService instead
     */
    metadataServiceEnabled?: pulumi.Input<boolean>;
    /**
     * Instance Template name
     */
    name?: pulumi.Input<string>;
    /**
     * The network attachments for this virtual server instance, including the primary network attachment.
     */
    networkAttachments?: pulumi.Input<pulumi.Input<inputs.IsInstanceTemplateNetworkAttachment>[]>;
    networkInterfaces?: pulumi.Input<pulumi.Input<inputs.IsInstanceTemplateNetworkInterface>[]>;
    /**
     * Unique Identifier of the Placement Group for restricting the placement of the instance
     */
    placementGroup?: pulumi.Input<string>;
    /**
     * The placement restrictions for the virtual server instance.
     */
    placementTargets?: pulumi.Input<pulumi.Input<inputs.IsInstanceTemplatePlacementTarget>[]>;
    /**
     * The primary network attachment for this virtual server instance.
     */
    primaryNetworkAttachment?: pulumi.Input<inputs.IsInstanceTemplatePrimaryNetworkAttachment>;
    /**
     * Primary Network interface info
     */
    primaryNetworkInterface?: pulumi.Input<inputs.IsInstanceTemplatePrimaryNetworkInterface>;
    /**
     * Profile info
     */
    profile?: pulumi.Input<string>;
    reservationAffinities?: pulumi.Input<pulumi.Input<inputs.IsInstanceTemplateReservationAffinity>[]>;
    /**
     * Instance template resource group
     */
    resourceGroup?: pulumi.Input<string>;
    /**
     * The amount of bandwidth (in megabits per second) allocated exclusively to instance storage volumes
     */
    totalVolumeBandwidth?: pulumi.Input<number>;
    /**
     * User data given for the instance
     */
    userData?: pulumi.Input<string>;
    volumeAttachments?: pulumi.Input<pulumi.Input<inputs.IsInstanceTemplateVolumeAttachment>[]>;
    /**
     * The volume bandwidth QoS mode for this virtual server instance.
     */
    volumeBandwidthQosMode?: pulumi.Input<string>;
    /**
     * VPC id
     */
    vpc?: pulumi.Input<string>;
    /**
     * Zone name
     */
    zone?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IsInstanceTemplate resource.
 */
export interface IsInstanceTemplateArgs {
    /**
     * The availability policy to use for this virtual server instance
     */
    availabilityPolicyHostFailure?: pulumi.Input<string>;
    bootVolume?: pulumi.Input<inputs.IsInstanceTemplateBootVolume>;
    /**
     * The catalog offering or offering version to use when provisioning this virtual server instance template. If an offering is specified, the latest version of that offering will be used. The specified offering or offering version may be in a different account in the same enterprise, subject to IAM policies.
     */
    catalogOffering?: pulumi.Input<inputs.IsInstanceTemplateCatalogOffering>;
    /**
     * The cluster network attachments to create for this virtual server instance. A cluster network attachment represents a device that is connected to a cluster network. The number of network attachments must match one of the values from the instance profile's `clusterNetworkAttachmentCount` before the instance can be started.
     */
    clusterNetworkAttachments?: pulumi.Input<pulumi.Input<inputs.IsInstanceTemplateClusterNetworkAttachment>[]>;
    /**
     * The confidential compute mode to use for this virtual server instance.If unspecified, the default confidential compute mode from the profile will be used.
     */
    confidentialComputeMode?: pulumi.Input<string>;
    /**
     * Unique Identifier of the Dedicated Host where the instance will be placed
     */
    dedicatedHost?: pulumi.Input<string>;
    /**
     * Unique Identifier of the Dedicated Host Group where the instance will be placed
     */
    dedicatedHostGroup?: pulumi.Input<string>;
    /**
     * If set to `true`, the system will create a link to the specified `target` trusted profile during instance creation. Regardless of whether a link is created by the system or manually using the IAM Identity service, it will be automatically deleted when the instance is deleted.
     */
    defaultTrustedProfileAutoLink?: pulumi.Input<boolean>;
    /**
     * The unique identifier or CRN of the default IAM trusted profile to use for this virtual server instance.
     */
    defaultTrustedProfileTarget?: pulumi.Input<string>;
    /**
     * Indicates whether secure boot is enabled for this virtual server instance.If unspecified, the default secure boot mode from the profile will be used.
     */
    enableSecureBoot?: pulumi.Input<boolean>;
    /**
     * image name
     */
    image?: pulumi.Input<string>;
    /**
     * SSH key Ids for the instance template
     */
    keys: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The metadata service configuration
     */
    metadataService?: pulumi.Input<inputs.IsInstanceTemplateMetadataService>;
    /**
     * Indicates whether the metadata service endpoint is available to the virtual server instance
     *
     * @deprecated Use metadataService instead
     */
    metadataServiceEnabled?: pulumi.Input<boolean>;
    /**
     * Instance Template name
     */
    name?: pulumi.Input<string>;
    /**
     * The network attachments for this virtual server instance, including the primary network attachment.
     */
    networkAttachments?: pulumi.Input<pulumi.Input<inputs.IsInstanceTemplateNetworkAttachment>[]>;
    networkInterfaces?: pulumi.Input<pulumi.Input<inputs.IsInstanceTemplateNetworkInterface>[]>;
    /**
     * Unique Identifier of the Placement Group for restricting the placement of the instance
     */
    placementGroup?: pulumi.Input<string>;
    /**
     * The primary network attachment for this virtual server instance.
     */
    primaryNetworkAttachment?: pulumi.Input<inputs.IsInstanceTemplatePrimaryNetworkAttachment>;
    /**
     * Primary Network interface info
     */
    primaryNetworkInterface?: pulumi.Input<inputs.IsInstanceTemplatePrimaryNetworkInterface>;
    /**
     * Profile info
     */
    profile: pulumi.Input<string>;
    reservationAffinities?: pulumi.Input<pulumi.Input<inputs.IsInstanceTemplateReservationAffinity>[]>;
    /**
     * Instance template resource group
     */
    resourceGroup?: pulumi.Input<string>;
    /**
     * The amount of bandwidth (in megabits per second) allocated exclusively to instance storage volumes
     */
    totalVolumeBandwidth?: pulumi.Input<number>;
    /**
     * User data given for the instance
     */
    userData?: pulumi.Input<string>;
    volumeAttachments?: pulumi.Input<pulumi.Input<inputs.IsInstanceTemplateVolumeAttachment>[]>;
    /**
     * The volume bandwidth QoS mode for this virtual server instance.
     */
    volumeBandwidthQosMode?: pulumi.Input<string>;
    /**
     * VPC id
     */
    vpc: pulumi.Input<string>;
    /**
     * Zone name
     */
    zone: pulumi.Input<string>;
}
