// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class IsVirtualNetworkInterfaceIp extends pulumi.CustomResource {
    /**
     * Get an existing IsVirtualNetworkInterfaceIp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IsVirtualNetworkInterfaceIpState, opts?: pulumi.CustomResourceOptions): IsVirtualNetworkInterfaceIp {
        return new IsVirtualNetworkInterfaceIp(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ibmcloud:index/isVirtualNetworkInterfaceIp:IsVirtualNetworkInterfaceIp';

    /**
     * Returns true if the given object is an instance of IsVirtualNetworkInterfaceIp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IsVirtualNetworkInterfaceIp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IsVirtualNetworkInterfaceIp.__pulumiType;
    }

    /**
     * The IP address.If the address has not yet been selected, the value will be `0.0.0.0`.This property may add support for IPv6 addresses in the future. When processing a value in this property, verify that the address is in an expected format. If it is not, log an error. Optionally halt processing and surface the error, or bypass the resource on which the unexpected IP address format was encountered.
     */
    declare public /*out*/ readonly address: pulumi.Output<string>;
    /**
     * The URL for this reserved IP.
     */
    declare public /*out*/ readonly href: pulumi.Output<string>;
    /**
     * The name for this reserved IP. The name is unique across all reserved IPs in a subnet.
     */
    declare public /*out*/ readonly name: pulumi.Output<string>;
    /**
     * The reserved ip identifier.
     */
    declare public readonly reservedIp: pulumi.Output<string>;
    /**
     * The resource type.
     */
    declare public /*out*/ readonly resourceType: pulumi.Output<string>;
    /**
     * The virtual network interface identifier.
     */
    declare public readonly virtualNetworkInterface: pulumi.Output<string>;

    /**
     * Create a IsVirtualNetworkInterfaceIp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IsVirtualNetworkInterfaceIpArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IsVirtualNetworkInterfaceIpArgs | IsVirtualNetworkInterfaceIpState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IsVirtualNetworkInterfaceIpState | undefined;
            resourceInputs["address"] = state?.address;
            resourceInputs["href"] = state?.href;
            resourceInputs["name"] = state?.name;
            resourceInputs["reservedIp"] = state?.reservedIp;
            resourceInputs["resourceType"] = state?.resourceType;
            resourceInputs["virtualNetworkInterface"] = state?.virtualNetworkInterface;
        } else {
            const args = argsOrState as IsVirtualNetworkInterfaceIpArgs | undefined;
            if (args?.reservedIp === undefined && !opts.urn) {
                throw new Error("Missing required property 'reservedIp'");
            }
            if (args?.virtualNetworkInterface === undefined && !opts.urn) {
                throw new Error("Missing required property 'virtualNetworkInterface'");
            }
            resourceInputs["reservedIp"] = args?.reservedIp;
            resourceInputs["virtualNetworkInterface"] = args?.virtualNetworkInterface;
            resourceInputs["address"] = undefined /*out*/;
            resourceInputs["href"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["resourceType"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IsVirtualNetworkInterfaceIp.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IsVirtualNetworkInterfaceIp resources.
 */
export interface IsVirtualNetworkInterfaceIpState {
    /**
     * The IP address.If the address has not yet been selected, the value will be `0.0.0.0`.This property may add support for IPv6 addresses in the future. When processing a value in this property, verify that the address is in an expected format. If it is not, log an error. Optionally halt processing and surface the error, or bypass the resource on which the unexpected IP address format was encountered.
     */
    address?: pulumi.Input<string>;
    /**
     * The URL for this reserved IP.
     */
    href?: pulumi.Input<string>;
    /**
     * The name for this reserved IP. The name is unique across all reserved IPs in a subnet.
     */
    name?: pulumi.Input<string>;
    /**
     * The reserved ip identifier.
     */
    reservedIp?: pulumi.Input<string>;
    /**
     * The resource type.
     */
    resourceType?: pulumi.Input<string>;
    /**
     * The virtual network interface identifier.
     */
    virtualNetworkInterface?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IsVirtualNetworkInterfaceIp resource.
 */
export interface IsVirtualNetworkInterfaceIpArgs {
    /**
     * The reserved ip identifier.
     */
    reservedIp: pulumi.Input<string>;
    /**
     * The virtual network interface identifier.
     */
    virtualNetworkInterface: pulumi.Input<string>;
}
