// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Lb extends pulumi.CustomResource {
    /**
     * Get an existing Lb resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LbState, opts?: pulumi.CustomResourceOptions): Lb {
        return new Lb(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ibmcloud:index/lb:Lb';

    /**
     * Returns true if the given object is an instance of Lb.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Lb {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Lb.__pulumiType;
    }

    /**
     * Connections value
     */
    declare public readonly connections: pulumi.Output<number>;
    /**
     * Datacenter name info
     */
    declare public readonly datacenter: pulumi.Output<string>;
    /**
     * Boolena value true if Load balncer is dedicated type
     */
    declare public readonly dedicated: pulumi.Output<boolean | undefined>;
    /**
     * true if High availability is enabled
     */
    declare public readonly haEnabled: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly hostname: pulumi.Output<string>;
    declare public /*out*/ readonly ipAddress: pulumi.Output<string>;
    /**
     * Security certificate ID
     */
    declare public readonly securityCertificateId: pulumi.Output<number | undefined>;
    declare public /*out*/ readonly sslEnabled: pulumi.Output<boolean>;
    /**
     * boolean value true if SSL offload is enabled
     */
    declare public readonly sslOffload: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly subnetId: pulumi.Output<number>;
    /**
     * Tags associated with resource
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;

    /**
     * Create a Lb resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LbArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LbArgs | LbState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LbState | undefined;
            resourceInputs["connections"] = state?.connections;
            resourceInputs["datacenter"] = state?.datacenter;
            resourceInputs["dedicated"] = state?.dedicated;
            resourceInputs["haEnabled"] = state?.haEnabled;
            resourceInputs["hostname"] = state?.hostname;
            resourceInputs["ipAddress"] = state?.ipAddress;
            resourceInputs["securityCertificateId"] = state?.securityCertificateId;
            resourceInputs["sslEnabled"] = state?.sslEnabled;
            resourceInputs["sslOffload"] = state?.sslOffload;
            resourceInputs["subnetId"] = state?.subnetId;
            resourceInputs["tags"] = state?.tags;
        } else {
            const args = argsOrState as LbArgs | undefined;
            if (args?.connections === undefined && !opts.urn) {
                throw new Error("Missing required property 'connections'");
            }
            if (args?.datacenter === undefined && !opts.urn) {
                throw new Error("Missing required property 'datacenter'");
            }
            resourceInputs["connections"] = args?.connections;
            resourceInputs["datacenter"] = args?.datacenter;
            resourceInputs["dedicated"] = args?.dedicated;
            resourceInputs["haEnabled"] = args?.haEnabled;
            resourceInputs["securityCertificateId"] = args?.securityCertificateId;
            resourceInputs["sslOffload"] = args?.sslOffload;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["ipAddress"] = undefined /*out*/;
            resourceInputs["sslEnabled"] = undefined /*out*/;
            resourceInputs["subnetId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Lb.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Lb resources.
 */
export interface LbState {
    /**
     * Connections value
     */
    connections?: pulumi.Input<number>;
    /**
     * Datacenter name info
     */
    datacenter?: pulumi.Input<string>;
    /**
     * Boolena value true if Load balncer is dedicated type
     */
    dedicated?: pulumi.Input<boolean>;
    /**
     * true if High availability is enabled
     */
    haEnabled?: pulumi.Input<boolean>;
    hostname?: pulumi.Input<string>;
    ipAddress?: pulumi.Input<string>;
    /**
     * Security certificate ID
     */
    securityCertificateId?: pulumi.Input<number>;
    sslEnabled?: pulumi.Input<boolean>;
    /**
     * boolean value true if SSL offload is enabled
     */
    sslOffload?: pulumi.Input<boolean>;
    subnetId?: pulumi.Input<number>;
    /**
     * Tags associated with resource
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a Lb resource.
 */
export interface LbArgs {
    /**
     * Connections value
     */
    connections: pulumi.Input<number>;
    /**
     * Datacenter name info
     */
    datacenter: pulumi.Input<string>;
    /**
     * Boolena value true if Load balncer is dedicated type
     */
    dedicated?: pulumi.Input<boolean>;
    /**
     * true if High availability is enabled
     */
    haEnabled?: pulumi.Input<boolean>;
    /**
     * Security certificate ID
     */
    securityCertificateId?: pulumi.Input<number>;
    /**
     * boolean value true if SSL offload is enabled
     */
    sslOffload?: pulumi.Input<boolean>;
    /**
     * Tags associated with resource
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
}
